
# TRACE and FISD

Under construction.

US corporate bonds are a highly relevant asset market, covering over 

The current chapter relies on this set of packages. 
```{r}
library(tidyverse)
library(lubridate)
library(dbplyr)
library(RSQLite)
library(RPostgres)
```

## Database and WRDS 

```{r}
tidy_finance <- dbConnect(SQLite(), "data/tidy_finance.sqlite",
  extended_types = TRUE
)

wrds <- dbConnect(
  Postgres(),
  host = "wrds-pgdata.wharton.upenn.edu",
  dbname = "wrds",
  port = 9737,
  sslmode = "require",
  user = Sys.getenv("user"),
  password = Sys.getenv("password")
)
```

Load data and filter
```{r}
# Main data
mergent <- tbl(wrds, in_schema("fisd", "fisd_mergedissue")) %>%
  filter(# senior, unsecured bonds not asset-backed
    security_level == "SEN",
    slob == "N", # secured lease obligation
    is.na(security_pledge),
    asset_backed == "N",
    defeased == "N", 
    bond_type %in% c("CDEB", # US Corporate Debentures
                     "CMTN", # US Corporate MTN (Medium Term Note)
                     "CMTZ", # US Corporate MTN Zero
                     "CZ", # US Corporate Zero,
                     "USBN"), # US Corporate Bank Note
    #mtn == "N", # exclude medium term notes
    pay_in_kind != "Y",
    yankee == "N",
    canadian == "N",
    foreign_currency == "N",
    coupon_type %in% c("F", "Z"), # fixed or zero coupon
    is.na(fix_frequency), # has to be NA if coupon is fixed
    coupon_change_indicator == "N", 
    interest_frequency %in% c("0", "1", "2", "4", "12"),
    rule_144a == "N", # publicly traded
    private_placement == "N", 
    defaulted == "N", # bankruptcy / default
    is.na(filing_date),
    is.na(settlement),
    convertible == "N",
    is.na(exchange),
    putable == "N",
    unit_deal == "N", # note: Bond issued with another security
    exchangeable == "N",
    perpetual == "N",
    preferred_security == "N")  %>%
  select(# Main variables
         complete_cusip, maturity, offering_amt, offering_date, dated_date,
         first_interest_date, interest_frequency, coupon, last_interest_date,
         day_count_basis, issue_id, issuer_id
         ) %>% 
  collect()
```

Only US domicile

```{r}
# SIC code and domicile
mergent_issuer <- tbl(wrds, in_schema("fisd", "fisd_mergedissuer")) %>% 
  select(issuer_id, sic_code, country_domicile) %>%
  collect()

# Merge and filter non-US firms
mergent <- mergent %>%
  inner_join(mergent_issuer, by = "issuer_id") %>%
  filter(country_domicile == "USA") %>%
  select(-country_domicile)
```

Save data

```{r}
# Save to database
mergent %>%
  dbWriteTable(tidy_finance, "mergent", ., overwrite = TRUE)
```

## TRACE

Create bins for bonds

```{r}
mergent_cusips <- mergent %>%
  pull(complete_cusip)

mergent_parts <- split(mergent_cusips, sample(1:1000, length(mergent_cusips), replace = T))
```

Loop cleaner

```{r}
for(part in 1:length(mergent_parts)) {
  cat("\n Starting: ", part, "\n  ->  ", as.character(Sys.time()), "\n")
  
  
  # Select respective part
  mergent_cusips_part <- gsub(".Rdata", "", mergent_parts[[part]])
  
  
  # Enhanced Trace ----------------------------------------------------------
  # Main file
  trace_all <- tbl(wrds, in_schema("trace", "trace_enhanced")) %>% 
    filter(cusip_id %in% mergent_cusips_part) %>%
    select(cusip_id, msg_seq_nb, orig_msg_seq_nb,
           entrd_vol_qt, rptd_pr, rpt_side_cd, cntra_mp_id,
           trd_exctn_dt, trd_exctn_tm, trd_rpt_dt, trd_rpt_tm, pr_trd_dt,
           trc_st, asof_cd, wis_fl, days_to_sttl_ct, stlmnt_dt, spcl_trd_fl) 
  
  # Enhanced Trace: Post 06-02-2012 -----------------------------------------
  # Trades (trc_st = T) and correction (trc_st = R)
  trace_post_TR <- trace_all %>% 
    filter((trc_st == "T" | trc_st == "R"),
           trd_rpt_dt >= as.Date("2012-02-06"))
  
  # Cancelations (trc_st = X) and correction cancelations (trc_st = C)
  trace_post_XC <- trace_all %>%
    filter((trc_st == "X" | trc_st == "C"),
           trd_rpt_dt >= as.Date("2012-02-06"))
  
  # Cleaning corrected and cancelled trades
  trace_post_TR <- trace_post_TR %>%
    anti_join(trace_post_XC,
              by = c("cusip_id", "msg_seq_nb", "entrd_vol_qt", 
                     "rptd_pr", "rpt_side_cd", "cntra_mp_id", 
                     "trd_exctn_dt", "trd_exctn_tm"))
  
  # Reversals (trc_st = Y)
  trace_post_Y <- trace_all %>%
    filter(trc_st == "Y",
           trd_rpt_dt >= as.Date("2012-02-06"))
  
  # Clean reversals
  ## match the orig_msg_seq_nb of the Y-message to the msg_seq_nb of the main message
  trace_post <- trace_post_TR %>%
    anti_join(trace_post_Y,
              by = c("cusip_id", "msg_seq_nb" = "orig_msg_seq_nb", 
                     "entrd_vol_qt", "rptd_pr", "rpt_side_cd", 
                     "cntra_mp_id", "trd_exctn_dt", "trd_exctn_tm"))
  
  
  # Enhanced TRACE: Pre 06-02-2012 ------------------------------------------
  # Cancelations (trc_st = C)
  trace_pre_C <- trace_all %>%
    filter(trc_st == "C",
           trd_rpt_dt < as.Date("2012-02-06"))
  
  # Trades w/o cancelations
  ## match the orig_msg_seq_nb of the C-message to the msg_seq_nb of the main message
  trace_pre_T <- trace_all %>%
    filter(trc_st == "T",
           trd_rpt_dt < as.Date("2012-02-06")) %>%
    anti_join(trace_pre_C, 
              by = c("cusip_id", "msg_seq_nb" = "orig_msg_seq_nb", 
                     "entrd_vol_qt", "rptd_pr", "rpt_side_cd", 
                     "cntra_mp_id", "trd_exctn_dt", "trd_exctn_tm"))
  
  # Corrections (trc_st = W) - W can also correct a previous W
  trace_pre_W <- trace_all %>%
    filter(trc_st == "W",
           trd_rpt_dt < as.Date("2012-02-06"))
  
  # Filter self-corrected Corrections 
  ## Corrections that are corrected (W's msg_seq_nb appears as another W's orig_msg_seq_nb) - corrected
  ## OR 
  ## Corrections that correct corrections (W's orig_msg_seq_nb is another W's msg_seq_nb) - correcting
  ## By cusip, trd_exctn_dt, & trd_exctn_tm
  trace_pre_W_self <- union_all(
    trace_pre_W %>% # Subsequently corrected corrections
      semi_join(trace_pre_W,
                by = c("cusip_id", "trd_exctn_dt", "trd_exctn_tm",
                       "msg_seq_nb" = "orig_msg_seq_nb")),
    trace_pre_W %>% # Correcting corrections
      semi_join(trace_pre_W,
                by = c("cusip_id", "trd_exctn_dt", "trd_exctn_tm",
                       "orig_msg_seq_nb" = "msg_seq_nb")))
  
  ## Correct self-corrections
  ### Trd_rpt is a numerical representation of reporting time 
  trace_pre_W_self_clean <- trace_pre_W_self %>%
    mutate(trd_rpt = trd_rpt_dt - as.Date("2000-01-01") + trd_rpt_tm/86400) %>%
    group_by(cusip_id, trd_exctn_dt, trd_exctn_tm) %>%
    mutate(across(c(-orig_msg_seq_nb, -trd_rpt, -cusip_id, -trd_exctn_dt, -trd_exctn_tm), ~ .x[trd_rpt == max(trd_rpt, na.rm = T)]),
           orig_msg_seq_nb = orig_msg_seq_nb[trd_rpt == min(trd_rpt, na.rm = T)]) %>%
    select(-trd_rpt) %>%
    group_by(cusip_id, trd_exctn_dt, trd_exctn_tm) %>%
    summarise(across(c(-cusip_id, -trd_exctn_dt, -trd_exctn_tm), ~ max(.x, na.rm = T)), .groups = 'drop') %>%
    select(colnames(trace_pre_W))
  
  ## Remove self-corrected corrections and combine all correct corrections
  trace_pre_W_all <- trace_pre_W %>%
    anti_join(trace_pre_W_self,
              by = c("cusip_id", "msg_seq_nb", "orig_msg_seq_nb", 
                     "trd_exctn_dt", "trd_exctn_tm", "rpt_side_cd",
                     "trd_rpt_dt", "trd_rpt_tm", "cntra_mp_id")) %>%
    union_all(trace_pre_W_self_clean)
  
  # Implement corrections
  ## Filter corrections with trades
  trace_pre_W_all <- trace_pre_W_all %>%
    semi_join(trace_pre_T, 
              by = c("cusip_id", "trd_exctn_dt",
                     "orig_msg_seq_nb" = "msg_seq_nb"))
  
  ## Combine non-corrected trades and the correct corrections
  trace_pre_TW <- trace_pre_T %>%
    anti_join(trace_pre_W_all, 
              by = c("cusip_id", "trd_exctn_dt",
                     "msg_seq_nb" = "orig_msg_seq_nb")) %>%
    union_all(trace_pre_W_all) 
  
  # Clean reversals
  ## Record reversals
  trace_pre_R <- trace_pre_TW %>%
    filter(asof_cd == 'R') %>%
    group_by(cusip_id, trd_exctn_dt, entrd_vol_qt, 
             rptd_pr, rpt_side_cd, cntra_mp_id) %>%
    arrange(trd_exctn_tm, trd_rpt_dt, trd_rpt_tm) %>%
    mutate(seq = row_number()) %>%
    ungroup()
  
  ## Remove reversals and the reversed trade
  trace_pre <- trace_pre_TW %>%
    filter(is.na(asof_cd) | !(asof_cd %in% c('R', 'X', 'D'))) %>%
    group_by(cusip_id, trd_exctn_dt, entrd_vol_qt, 
             rptd_pr, rpt_side_cd, cntra_mp_id) %>%
    arrange(trd_exctn_tm, trd_rpt_dt, trd_rpt_tm) %>%
    mutate(seq = row_number()) %>%
    ungroup() %>%
    anti_join(trace_pre_R,
              by = c("cusip_id", "trd_exctn_dt", "entrd_vol_qt", 
                     "rptd_pr", "rpt_side_cd", "cntra_mp_id", "seq")) %>%
    select(-seq)
  
  
  # Agency trades -----------------------------------------------------------
  # Combine pre and post trades
  trace_clean <- trace_post %>%
    union_all(trace_pre)
  
  # Keep angency sells and unmatched agency buys
  ## Agency sells
  trace_agency_sells <- trace_clean %>%
    filter(cntra_mp_id == "D",
           rpt_side_cd == "S")
  
  # Agency buys that are unmatched
  trace_agency_buys_filtered <- trace_clean %>%
    filter(cntra_mp_id == "D",
           rpt_side_cd == "B") %>%
    anti_join(trace_agency_sells, 
              by = c("cusip_id", "trd_exctn_dt", 
                     "entrd_vol_qt", "rptd_pr"))
  
  # Agency clean
  trace_clean <- trace_clean %>%
    filter(cntra_mp_id == "C") %>%
    union_all(trace_agency_sells) %>%
    union_all(trace_agency_buys_filtered) 
  
  
  # Additional Filters ------------------------------------------------------
  trace_add_filters <- trace_clean %>%
    mutate(days_to_sttl_ct2 = stlmnt_dt - trd_exctn_dt) %>%
    filter(is.na(days_to_sttl_ct) | as.numeric(days_to_sttl_ct) <= 7,
           is.na(days_to_sttl_ct2) | as.numeric(days_to_sttl_ct2) <= 7,
           wis_fl == "N",
           is.na(spcl_trd_fl) | spcl_trd_fl == "",
           is.na(asof_cd) | asof_cd == "")
  
  
  # Collection --------------------------------------------------------------
  # Only collect necessary columns
  trace_final <- trace_add_filters %>%
    arrange(cusip_id, trd_exctn_dt, trd_exctn_tm) %>%
    select(cusip_id, trd_exctn_dt, trd_exctn_tm, rptd_pr, entrd_vol_qt, rpt_side_cd, cntra_mp_id) %>%
    collect() %>%
    mutate(trd_exctn_tm = format(as_datetime(trd_exctn_tm), "%H:%M:%S")) 
  
  # Save
  trace_final %>%
    dbWriteTable(conn = tidy_finance, 
                 name = paste0("trace_", formatC(part, format = "d", width = 4, flag = "0")),
                 value = .,
                 overwrite = TRUE)


cat("  <- ", as.character(Sys.time()), "\n")
rm(list = ls()[-which(ls() %in% c("tidy_finance", "wrds", "mergent_parts"))])
}
```

