project:
  type: website
  output-dir: docs

bibliography:
  - assets/bib/book.bib
  - assets/bib/packages-r.bib
  - assets/bib/packages-python.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

execute:
  freeze: auto
  eval: true
  echo: true
  warning: true
  message: false
  cache: false

format:
  html:
    theme:
      light: [cosmo, assets/scss/theme-light.scss]
    css: assets/css/global.css
    toc: true
    section-divs: true
    number-sections: false
    embed-resources: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.tidy-finance\.org'
    citations-hover: true
    footnotes-hover: true
    code-link: false
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    lightbox: auto
    include-after-body: assets/html/footer.html

website:
  title: "Tidy Finance"
  site-url: https://www.tidy-finance.org
  image: assets/img/cover.png
  repo-url: https://github.com/tidy-finance/website
  repo-actions: source
  description: "An opinionated approach on empirical research in financial economics"
  favicon: assets/img/favicon.png
  open-graph: true
  page-navigation: true
  bread-crumbs: false
  google-analytics:
    tracking-id: "G-DH3KZSMJ5W"
    anonymze-ip: true
  cookie-consent:
    type: express
    style: interstitial
    palette: light
  navbar:
    logo: assets/img/logo-website-white.png
    pinned: false
    left:
      - href: r/index.qmd
        text: R
      - href: python/index.qmd
        text: Python
      - href: blog.qmd
        text: Blog
      - href: contribute.qmd
        text: Contribute
      - href: support.qmd
        text: Support
      - href: https://talks.tidy-finance.org
        text: Talks
      - href: workshops/reproducible-research-workflows.qmd
        text: Workshops
  sidebar:
    - id: tidy-finance-with-r
      style: "floating"
      search: true
      collapse-level: 0
      pinned: true
      contents:
        - section: "Tidy Finance with R"
          contents:
            - r/index.qmd
        - section: "Prerequisits"
          contents:
            - r/setting-up-your-environment.qmd
            - r/the-tidyfinance-r-package.qmd
        - section: "Getting Started"
          contents:
            - r/working-with-stock-returns.qmd
            - r/modern-portfolio-theory.qmd
            - r/capital-asset-pricing-model.qmd
            - r/financial-statement-analysis.qmd
            - r/discounted-cash-flow-analysis.qmd
        - section: "Financial Data"
          contents:
            - r/accessing-and-managing-financial-data.qmd
            - r/wrds-crsp-and-compustat.qmd
            - r/trace-and-fisd.qmd
            - r/other-data-providers.qmd
        - section: "Asset Pricing"
          contents:
            - r/beta-estimation.qmd
            - r/univariate-portfolio-sorts.qmd
            - r/size-sorts-and-p-hacking.qmd
            - r/value-and-bivariate-sorts.qmd
            - r/replicating-fama-and-french-factors.qmd
            - r/fama-macbeth-regressions.qmd
        - section: "Modeling and Machine Learning"
          contents:
            - r/fixed-effects-and-clustered-standard-errors.qmd
            - r/difference-in-differences.qmd
            - r/factor-selection-via-machine-learning.qmd
            - r/option-pricing-via-machine-learning.qmd
        - section: "Portfolio Optimization"
          contents:
            - r/parametric-portfolio-policies.qmd
            - r/constrained-optimization-and-backtesting.qmd
        - section: "Appendix"
          contents:
            - r/wrds-dummy-data.qmd
            - r/cover-and-logo-design.qmd
            - r/clean-enhanced-trace-with-r.qmd
            - r/proofs.qmd
            - r/hex-sticker.qmd
            - r/changelog.qmd
    - id: tidy-finance-with-python
      style: "floating"
      search: true
      collapse-level: 0
      pinned: true
      contents:
        - section: "Tidy Finance with Python"
          contents:
            - python/index.qmd
        - section: "Prerequisits"
          contents:
            - python/setting-up-your-environment.qmd
            - python/the-tidyfinance-python-package.qmd
        - section: "Getting Started"
          contents:
            - python/working-with-stock-returns.qmd
            - python/modern-portfolio-theory.qmd
            - python/capital-asset-pricing-model.qmd
            - python/financial-statement-analysis.qmd
            - python/discounted-cash-flow-analysis.qmd
        - section: "Financial Data"
          contents:
            - python/accessing-and-managing-financial-data.qmd
            - python/wrds-crsp-and-compustat.qmd
            - python/trace-and-fisd.qmd
            - python/other-data-providers.qmd
        - section: "Asset Pricing"
          contents:
            - python/beta-estimation.qmd
            - python/univariate-portfolio-sorts.qmd
            - python/size-sorts-and-p-hacking.qmd
            - python/value-and-bivariate-sorts.qmd
            - python/replicating-fama-and-french-factors.qmd
            - python/fama-macbeth-regressions.qmd
        - section: "Modeling and Machine Learning"
          contents:
            - python/fixed-effects-and-clustered-standard-errors.qmd
            - python/difference-in-differences.qmd
            - python/factor-selection-via-machine-learning.qmd
            - python/option-pricing-via-machine-learning.qmd
        - section: "Portfolio Optimization"
          contents:
            - python/parametric-portfolio-policies.qmd
            - python/constrained-optimization-and-backtesting.qmd
        - section: "Appendix"
          contents:
            - python/wrds-dummy-data.qmd
            - python/cover-image.qmd
            - python/clean-enhanced-trace-with-python.qmd
            - python/proofs.qmd
            - python/colophon.qmd
            - python/changelog.qmd
      
editor: source
