---
title: Changelog
---
- [May 23, 2023, Commit d5e355c:](https://github.com/tidy-finance/website/commit/d5e355ca6cf117bcc193376124c46ca1b2e9ed1d) We update the workflow to `collect()` tables from `tify_finance.sqlite`: To make variable selection more obvious, we now explicitly `select()` columns before collecting. As part of the pull request (Commit 91d3077)[https://github.com/tidy-finance/website/pull/42/commits/91d3077ee75a3ab71db684001d0562a53031c73c], we now select excess returns instead of net returns in the Chapter [Fama-MacBeth Regressions](https://www.tidy-finance.org/fama-macbeth-regressions.html).
- [May 20, 2023, Commit be0f0b4:](https://github.com/tidy-finance/website/commit/be0f0b4b156487299369c682a4d47d1d10ec5485) We include `NA`-observations in the Mergent filters in Chapter [TRACE and FISD](https://www.tidy-finance.org/trace-and-fisd.html).
- [May 17, 2023, Commit 2209bb1:](https://github.com/tidy-finance/website/commit/2209bb133d2080eae52cbbc5ec14e4550ff186d3) We changed the `assign_portfolio()`-functions in Chapters [Univariate Portfolio Sorts](https://www.tidy-finance.org/univariate-portfolio-sorts.html), [Size Sorts and p-Hacking](https://www.tidy-finance.org/size-sorts-and-p-hacking.html), [Value and Bivariate Sorts](https://www.tidy-finance.org/value-and-bivariate-sorts.html), and [Replicating Fama and French Factors](https://www.tidy-finance.org/replicating-fama-and-french-factors.html). Additionally, we added a small explanation to potential issues with the function for clustered sorting variables in Chapter [Univariate Portfolio Sorts](https://www.tidy-finance.org/univariate-portfolio-sorts.html).
- [May 12, 2023, Commit 54b76d7:](54b76d7c1977c3759ed8bd641940d17add1a755b) We removed magic numbers in Chapter [Introduction to Tidy Finance](https://www.tidy-finance.org/introduction-to-tidy-finance.html#the-efficient-frontier) and introduced the `scales` packages already in the introduction chapter to reduce scaling issues in figures. - [Mar. 30, 2023, Issue 29:](https://github.com/tidy-finance/website/issues/29) We upgraded to `tidyverse` 2.0.0 and R 4.2.3 and removed all explicit loads of `lubridate`.
- [Feb. 15, 2023, Commit bfda6af: ](https://github.com/tidy-finance/website/commit/bfda6af6169a42f433568e32b7a9cce06cb948ac) We corrected an error in the calculation of the annualized average return volatility in the Chapter [Introduction to Tidy Finance](https://www.tidy-finance.org/introduction-to-tidy-finance.html#the-efficient-frontier).
- [Mar. 06, 2023, Commit 857f0f5: ](https://github.com/tidy-finance/website/commit/857f0f5893a8e7e4c2b4475e1461ebf3d0abe2d6) We corrected an error in the label of [Figure 6](https://www.tidy-finance.org/introduction-to-tidy-finance.html#fig-106), which wrongly claimed to show the efficient tangency portfolio.
- [Mar. 09, 2023, Commit fae4ac3: ](https://github.com/tidy-finance/website/commit/fae4ac3fd12797d66a48f43af3d8e84ded694f13) We corrected a typo in the definition of the power utility function in Chapter [Portfolio Performance](https://www.tidy-finance.org/parametric-portfolio-policies.html#portfolio-performance). The utility function implemented in the code is now consistent with the text. 
