---
title: "Contribute to Tidy Finance"
sidebar: false
---

Join our mission to support reproducible finance by contributing to the Tidy Finance Blog. The blog follows our endeavors to increase transparency in financial economics and opens a new channel for you. We actively encourage the finance community to share their insights on coding.

>We hope to inspire others to share their code publicly and take part in our journey toward more reproducible research in the future.

Tidy Finance is an open-source project to augment how research is conducted. We hope to change the way people think about sharing their code. The Tidy Finance Blog is open to everybody who wants to share their code, discuss paper replication, preparation of typical datasets or highlight novel empirical applications in financial economics. The blog is an excellent tool to promote your research and share your thought processes with the community.

>We believe that the need for precise academic writing does not stop where the code begins.

We strive to make Tidy Finance a trusted, up-to-date resource for all topics in financial economics. Therefore, we commit our time to ensure high-quality content - a commitment that we extend to the Tidy Finance Blog by providing editorial-like processes. While we aim to be as open as possible, we will also carefully assess all contributions. 

## Who should contribute to the Tidy Finance Blog?

Everybody should consider writing a blog post on Tidy Finance. We do not exclude anybody from the finance community. We always appreciate relevant contributions that help the target audiences of Tidy Finance (i.e., researchers, students, and professionals). Let us move forward together.

## How can I contribute?

If you want to contribute to the Tidy Finance Blog, we provide a simple three-step process for your blog post.  

1. Send a proposal for your blog post to [blog\@tidy-finance.org](mailto:blog@tidy-finance.org). 
2. After our confirmation, write and submit your blog post.
3. Work with us on potential revisions before reading your published post.

We are grateful for every contribution. This process is our attempt to provide fairness to all parties. From the perspective of the readers, the other authors, and the whole project, ensuring the quality and relevance of all contributions is paramount. Hence, we cannot publish all blog posts without thoroughly reviewing the submissions.

We ask you to submit a proposal before you write an entire post to ensure your efforts are not wasted. In this proposal, we want to learn about your idea and how it will contribute to Tidy Finance. Therefore, do not hesitate to submit a proposal. We guarantee full anonymity and an open attitude to your suggestion. Nevertheless, we do not make promises regarding a positive decision.

Once you receive our thumbs-up, you can start working on your contribution. The target format is a quarto document we can render as part of our website repository. When you have a first draft ready, send us an HTML output, and we will provide timely feedback. 

Finally, we will publish your post on the Tidy Finance blog with your name added to the list of contributors to reproducible finance. Unfortunately, we cannot provide you with a cape. Then again, not all heroes wear capes. 

## Part of the future

The Tidy Finance Blog is the place to contribute stand-alone applications in financial economics with guaranteed quality and relevance. While you publish under an [open-source license](index.qmd#license), you retain sole authorship of your work. Furthermore, in future editions of “Tidy Finance with R,” we will acknowledge external contributions directly by referring to the Tidy Finance blog and citing your work.

## What if I do not use the tidyverse or R? 

Tidy Finance is strongly connected to the tidyverse and R. Yet, we do not rule out extending our horizon and learning new tricks. You can make non-tidyverse and non-R suggestions. However, we need a sufficient reason to break with our tradition.
