--- 
title: "Tidy Finance"
author: "Christoph Scheuch, Patrick Weiss and Stefan Voigt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: voigtstefan/tidy_finance
description: "Tidy Finance with R"
---

# Prerequisites

This set of exercises is written for the students of the lecture "Advanced Empirical Finance: Topics and Data Science".
The exercise sets partially subsume work I created with my colleagues Christoph Scheuch and Patrick Weiss for the book *Tidy Finance*. You are very welcome to give us feedback on *every* aspect of the book such that we can improve the codes, explanations and general structure. Please contact me if you spot typos, mistakes or other issues that deserve more attention. 

Needless to say, you should try to solve each question on your own before you refer to my proposed answers. Optimally, you discuss issues with your peers, try to find hints either in the lecture slides or online, There are many ways to get answer to your questions, most directly you can simply post your questions on StackExchange or Absalon. 

As an absolute minimum before trying to solve the following exercises, make sure you are familiar with Garrett Grolemund's and Hadley Wickham's excellent book [R for Data Science](https://r4ds.had.co.nz/). I will make further information or references available on Absalon. 

Welcome!

In the course "Advanced Empirical Finance" we repeatedly ask: (How) can state-of-the art methods improve financial decision-making?

While the lecture covers all relevant theoretical aspects and is based on very recent academic papers, you should spend most of your effort on this course on actually doing empirical work! Get your computer ready to work on real problems for financial applications and discuss your code with your peers to acquire the necessary skills to make a difference either in the Finance industry or academia. 

## Things to get done before the first lecture

To dive right into it, there are a couple of prerequisites you should get done before the first lecture:

- [Install R and RStudio](https://rstudio-education.github.io/hopr/starting.html#starting). To get a walk-through of the installation (for every major operating system), follow the steps outlined [in this summary](https://rstudio-education.github.io/hopr/starting.html#starting). Should be done in few clicks. If you wonder about the difference: R is an open-source  language and environment for statistical computing and graphics, free to download and use. While R runs computations, RStudio is an integrated development environment (IDE) that provides an interface by adding many convenient features and tools. I suggest you do all coding exclusively with RStudio during the course (and beyond).
- Open RStudio and  run  the  following  line  of  code: `install.packages("tidyverse")`. Not sure how it works? You find helpful information on how to install packages in this [brief summary](https://rstudio-education.github.io/hopr/packages2.html). The tidyverse is “a framework for managing data that aims at making the cleaning and preparing steps much easier”. We are going to work almost exclusively with tidyverse packages.
- Check if everything works: Open Rstudio and type `library(tidyverse)`. You should then get a message like in the picture below.  Works? Done with the software setup!  

## What is R?

In this course we work with R. Together with Python, R is nowadays the de facto standard tool in finance and is unparalleled when it comes to handle data science applications.

*But so far I learned to code with Python, Ox, Matlab, …*

Excellent if you have prior knowledge in another coding language. Your start with R will be way easier. Also, as a Python user you can actually run your Python code in R (and vice versa) - so if you have already written some analysis for a prior project, no need to translate everything! If you are interested to do this at some point in time, check out this resource (we will provide a brief TA session on cross-platform operability later in the course).

*I have no experience whatsoever with programming*

Great, you nevertheless make the bar for the course requirements. We will start entirely from scratch (but with a really steep learning curve). Besides the applications in Finance, we will focus on state-of-the-art data science concepts that cover the entire life cycle of a successful empirical analysis. No matter if we consider a research project, a thesis, seminar paper or a thorough portfolio back testing procedure at an investment bank: the challenges are always similar. The figure below illustrates the components we will talk about: How do we get R connected to our datasets? How can we clean the data such that our analysis makes sense? How to visualize or change variables in order to estimate parameters or make financial decisions? And, finally, how can we communicate our results such that we are sure that our analysis is reliable, correct and flexible enough to quickly find out what happens if we have to change some input parameters.

*This sounds like a lot of work on the data science front. How do I get started?*

There are a couple of ways for you to get started, below a list with relevant material and suggestions.

1. As a member of this course you have **free access to all online tutorials of DataCamp** which provides excellent browser-based tutorials on the basics of R, the tidyverse and a lot of applications in Finance. In order to enjoy the benefits of completely free access, sign up to our own course site using [this link](https://www.datacamp.com/users/sign_up?group_invite=true&group_name=Advanced+Empirical+Finance%3A+Topics+and+Data+Science&group_type=academic&policy_version=&redirect=https%3A%2F%2Fwww.datacamp.com%2Fgroups%2Fshared_links%2F5942f03f4aed010fb1498f59b2613587bc1eae4c8410835827a65b4049731a22%3Fdc_referrer%3Dmain-group%26tos%3Dtrue) (careful: registration is only possible with an econ.ku.dk mail domain)
1. Only way to learn how to code is by getting your hands dirty. Make sure your system is ready to go by completing all technical requirements.
1. A very gentle and good introduction into the workings of R can be found [here](https://rstudio-education.github.io/hopr/project-1-weighted-dice.html). Once you are done with setting up R on your machine, try to follow the "weighted dice project".
1. The main book of this course is available online and for free: [R for Data Science](https://r4ds.had.co.nz/introduction.html) by Hadley Wickham and Garrett Grolemund explains everything we need. Throughout the course we will cover almost the entire content of the book. I advise you to read the first 3 Chapters for a gentle dive into the material before the lectures starts.

*Help, I am stuck! Where do I get help?*

To struggle in the beginning is absolutely fine, and you are not alone. Indeed, there are around 40 other students in the course that have similar questions. Make use of this community!

1. You can always post questions in the Discussion forum. The TA's, your colleagues and I will try to help you out.
1. You do not have to do all the work on your own. Search for a coding buddy to discuss your problems in teams (for the assignments you can hand-in in groups of up to 3 students!).
1. If you still feel like you are stuck (which is fine and can happen) reach out directly in class or during the office hour!