---
pagetitle: "Tidy Finance"
page-layout: custom
section-divs: false
toc: false
css: styling/custom.css
editor: source
description: | 
  An opinionated approach on empirical research in financial economics.
hide-description: true 
--- 

::: {.content-block}

# Welcome to Tidy Finance  

> Tidy Finance is an opinionated approach to empirical research in financial economics - a fully transparent, open-source code base in multiple programming languages.

## Join Tidy Finance

- Learn about empirical applications based on a fully transparent code base
- Teach students the importance of reproducible research using tidy principles
- Start your next finance research project one step ahead with a Tidy Finance basis
- [Support](support.qmd) the maintenance of our open-source project
- [Contribute](contribute.qmd) to mission of reproducible finance via our blog
- Reach out with ideas, suggestions, and feedback via [contact\@tidy-finance.org](mailto:contact@tidy-finance.org)

## Choose your language

::: {.center}
<button class="btn-action-r" onclick="window.location.href='r/index.html';">
  R
</button>
<button class="btn-action-python" onclick="window.location.href='python/index.html';">
  Python
</button>
:::

:::