{
  "hash": "d276be8fdbad4a7eed979f06a91e683a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Accessing and Managing Financial Data\naliases:\n  - ../accessing-and-managing-financial-data.html\n  - ../r/accessing-and-managing-financial-data.html\n  - ../python/accessing-and-managing-financial-data.html\nmetadata:\n  pagetitle: Accessing and Managing Financial Data\n  description-meta: Download and organize open-source financial data using the programming languages R and Python.\n---\n\n\n::: {.cell}\n\n:::\n\n\nIn this chapter, we suggest a way to organize your financial data. Everybody who has experience with data is also familiar with storing data in various formats like CSV, XLS, XLSX, or other delimited value storage. Reading and saving data can become very cumbersome in the case of using different data formats, both across different projects and across different programming languages. Moreover, storing data in delimited files often leads to problems with respect to column type consistency. For instance, date-type columns frequently lead to inconsistencies across different data formats and programming languages.\n\nThis chapter shows how to import different open source data sets. Specifically, our data comes from the application programming interface (API) of Yahoo Finance, a downloaded standard CSV file, an XLSX file stored in a public Google Drive repository, and other macroeconomic time series that can be scraped directly from a website.\\index{API}\\index{Web scraping} We show how to process these raw data, as well as how to take a shortcut using the `tidyfinance` package, which provides a consistent interface to tidy financial data. We store all the data in a *single* database, which serves as the only source of data in subsequent chapters. We conclude the chapter by providing some tips on managing databases.\\index{Database}\n\nWe use the following packages throughout this chapter. Later on, we load more packages in the sections where we need them.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyfinance)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyfinance' was built under R version 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(scales)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport polars as pl\nimport tidyfinance as tf\nimport io\nimport re\nimport zipfile\nfrom curl_cffi import requests\n```\n:::\n\n\n:::\n\n\n::: {.cell}\n\n:::\n\n\nMoreover, we initially define the date range for which we fetch and store the financial data, making future data updates tractable. In case you need another time frame, you can adjust the dates below. Our data starts with 1960 since most asset pricing studies use data from 1962 on.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstart_date <- ymd(\"1960-01-01\")\nend_date <- ymd(\"2024-12-31\")\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstart_date = \"1960-01-01\"\nend_date = \"2024-12-31\"\n```\n:::\n\n\n:::\n\n## Fama-French Data\n\nWe start by downloading some famous Fama-French factors [e.g., @Fama1993] and portfolio returns commonly used in empirical asset pricing. The data are freely available from [Prof. Kenneth French's finance data library](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html), but the raw files come in a rather idiosyncratic format.\\index{Data!Fama-French factors} \\index{Kenneth French homepage} If you access the data through the website, the manual *raw* workflow looks like this:\n\n1.  Open the data library website.\n1.  Find the right dataset.\n1.  Download a ZIP file.\n1.  Extract the CSV inside.\n1.  Select the relevant data table from the file and import it.\n1.  Clean the dates, scale the returns, fix the column names, and handle missing values.\n\nDoing this once is fine; doing it repeatedly across projects is exactly the kind of boilerplate that is easy to get wrong and annoying to maintain. It is therefore natural to automate these steps. In fact, this is precisely what the `tidyfinance` package does under the hood. In this section, we first reproduce the source code behind the package so that you understand what happens when you download Fama-French data, and then we show the convenient shortcut.\n\n### From manual steps to a download script\n\nA minimal download script mirrors the manual steps one by one. To fetch a Fama-French dataset, we first construct the URL of the corresponding ZIP archive on Kenneth French's server. Each dataset is identified by the file name of its archive; the *Fama/French 3 Factors* set, for instance, lives in `F-F_Research_Data_Factors_CSV.zip`.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_url <- \"https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/\"\nfile_name <- \"F-F_Research_Data_Factors_CSV.zip\"\nurl <- paste0(base_url, file_name)\n```\n:::\n\n\nNext, we replace the browser download with an HTTP request using the `httr2` [@httr2] package and store the archive in a temporary file. We attach a browser-like user agent because Kenneth French's server rejects requests that do not provide one.\\index{httr2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(httr2)\n\ntmp_zip <- tempfile(fileext = \".zip\")\n\nrequest(url) |>\n  req_user_agent(\n    \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\"\n  ) |>\n  req_perform(path = tmp_zip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<httr2_response>\nGET https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_CSV.zip\nStatus: 200 OK\nContent-Type: application/x-zip-compressed\nBody: On disk 'C:\\Users\\ncj140\\AppData\\Local\\Temp\\RtmpiAW7BK\\file70ac5117797e.zip' (13044 bytes)\n```\n\n\n:::\n:::\n\n\nThe archive contains a single CSV file, which we extract into a temporary directory and read line by line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmp_dir <- tempfile()\ndir.create(tmp_dir)\ncsv_file <- unzip(tmp_zip, exdir = tmp_dir)[1]\nraw_lines <- readLines(csv_file, warn = FALSE)\n```\n:::\n\n\nThe raw file starts with several lines of descriptive text, followed by one or more data tables (e.g., monthly returns and a block of annual summary rows). To emulate *scrolling down until the numbers start*, we flag every line that begins with a date key---an optional run of spaces followed by a digit---and keep the first contiguous block of such lines. The line directly above that block holds the column names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_data <- grepl(\"^\\\\s*[0-9]\", raw_lines)\nruns <- rle(is_data)\nfirst_run <- which(runs$values)[1]\npreceding <- sum(runs$lengths[seq_len(first_run - 1)])\nfirst_data <- preceding + 1\nlast_data <- preceding + runs$lengths[first_run]\nblock <- raw_lines[c(first_data - 1, first_data:last_data)]\n```\n:::\n\n\nWe hand this block to `read.csv()` and label the first (unnamed) column `date`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff3_monthly_raw <- read.csv(text = block, check.names = FALSE)\nnames(factors_ff3_monthly_raw)[1] <- \"date\"\nfactors_ff3_monthly_raw <- as_tibble(factors_ff3_monthly_raw)\nfactors_ff3_monthly_raw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,198 × 5\n    date `Mkt-RF`   SMB   HML    RF\n   <int>    <dbl> <dbl> <dbl> <dbl>\n1 192607     2.89 -2.55 -2.39  0.22\n2 192608     2.64 -1.14  3.81  0.25\n3 192609     0.38 -1.36  0.05  0.23\n4 192610    -3.27 -0.14  0.82  0.32\n5 192611     2.54 -0.11 -0.61  0.31\n# ℹ 1,193 more rows\n```\n\n\n:::\n:::\n\n\nFinally, we still have to clean the data. The set *Fama/French 3 Factors* contains the return time series of the market `mkt_excess`, size `smb`, and value `hml` factors alongside the risk-free rate `risk_free`.\\index{Factor!Market}\\index{Factor!Size}\\index{Factor!Value}\\index{Factor!Profitability}\\index{Factor!Investment}\\index{Risk-free rate} Cleaning involves a handful of steps:\n\n-   Parse the integer date keys (e.g., `192607`) into proper dates.\n-   Replace Kenneth French's missing-value codes (`-99.99` and `-999`) with `NA`.\n-   Convert the returns from percent to decimals by dividing by 100.\n-   Standardize the column names (lower case, `Mkt-RF` to `mkt_excess`, and `RF` to `risk_free`).\n-   Filter the data to the desired date range.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff3_monthly <- factors_ff3_monthly_raw |>\n  mutate(\n    date = floor_date(ymd(str_c(date, \"01\")), \"month\"),\n    across(-date, as.numeric),\n    across(-date, ~ na_if(., -99.99)),\n    across(-date, ~ na_if(., -999)),\n    across(-date, ~ . / 100)\n  ) |>\n  rename_with(str_to_lower, -date) |>\n  rename(mkt_excess = `mkt-rf`, risk_free = rf) |>\n  filter(date >= start_date & date <= end_date)\nfactors_ff3_monthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 780 × 5\n  date       mkt_excess     smb     hml risk_free\n  <date>          <dbl>   <dbl>   <dbl>     <dbl>\n1 1960-01-01    -0.0698  0.0212  0.0265    0.0033\n2 1960-02-01     0.0116  0.006  -0.0197    0.0029\n3 1960-03-01    -0.0163 -0.0055 -0.0275    0.0035\n4 1960-04-01    -0.0171  0.0022 -0.0214    0.0019\n5 1960-05-01     0.0312  0.0129 -0.0373    0.0027\n# ℹ 775 more rows\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndataset = \"F-F_Research_Data_Factors\"\nbase_url = \"http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/\"\nurl = f\"{base_url}{dataset}_CSV.zip\"\n```\n:::\n\n\nNext, we replace the browser download with an HTTP request and extract the ZIP in memory.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nresp = requests.get(url)\nresp.raise_for_status()\n\nwith zipfile.ZipFile(io.BytesIO(resp.content)) as zf:\n    file_name = zf.namelist()[0]  # Ken French ZIPs contain one file\n    raw_text = zf.read(file_name).decode(\"latin1\")\n```\n:::\n\n\nThe most important part of this chunk is the `requests.get()` call. This is the moment where we replace all the manual browser work (open the website, click download, save the file) with a single, reproducible line of code. Then, calling `raise_for_status()` ensures we stop immediately if the server returns an error (e.g., HTTP 404 or 500) instead of quietly handling a broken file. Once this succeeds, `resp.content` is guaranteed to contain valid ZIP bytes that we can open in memory.\n\nThe raw file contains documentation text followed by the actual data table(s). To emulate *scrolling down until the numbers start*, we split the file into blocks and keep the long one that contains the table.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nchunks = raw_text.split(\"\\r\\n\\r\\n\")\ntable_text = max(chunks, key=len)\n```\n:::\n\n\nWithin this block, the first CSV header line starts at the first line beginning with a comma. We add a \"Date\" label for the first column and pass everything to `pl.read_csv()`, which accepts the raw bytes directly. The numeric fields in the raw file carry leading spaces (e.g., `  2.89`), which `polars` does not strip automatically — such values are read as strings. We therefore trim the whitespace and cast all non-date columns to floats.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmatch = re.search(r\"^\\s*,\", table_text, flags=re.M)\nstart = match.start()\ncsv_text = \"Date\" + table_text[start:]\n\nfactors_ff3_monthly_raw = pl.read_csv(csv_text.encode(\"latin1\")).with_columns(\n    pl.exclude(\"Date\").cast(pl.String).str.strip_chars().cast(pl.Float64)\n)\n```\n:::\n\n\nAt this point, the `Date` column still consists of integer date codes with different lengths depending on the frequency. We need a bit of logic to convert them into a proper date column.\n\n\n::: {.cell}\n\n```{.python .cell-code}\ns = factors_ff3_monthly_raw[\"Date\"].cast(pl.String)\nn = s.str.len_chars()\n\nif (n == 8).all():  # daily: YYYYMMDD\n    date = s.str.to_date(\"%Y%m%d\")\nelif (n == 6).all():  # monthly: YYYYMM\n    date = (s + \"01\").str.to_date(\"%Y%m%d\")\nelif (n == 4).all():  # annual: YYYY, assigned to year-end\n    date = (s + \"1231\").str.to_date(\"%Y%m%d\")\nelse:\n    raise ValueError(\"Unknown date format in Fama–French index.\")\n\nfactors_ff3_monthly_raw = factors_ff3_monthly_raw.with_columns(date=date).drop(\"Date\")\n```\n:::\n\n\nFinally, we still have to clean the data. The set *Fama/French 3 Factors* contains the return time series of the market `mkt_excess`, size `smb`, and value `hml` factors alongside the risk-free rate `risk_free`.\\index{Factor!Market}\\index{Factor!Size}\\index{Factor!Value}\\index{Factor!Profitability}\\index{Factor!Investment}\\index{Risk-free rate} Cleaning involves a handful of steps:\n\n-   Replace Kenneth French's missing-value codes (`-99.99` and `-999`) with actual missing values.\n-   Convert the returns from percent to decimals by dividing by 100.\n-   Standardize the column names (lower case, `Mkt-RF` to `mkt_excess`, and `RF` to `risk_free`).\n-   Filter the data to the desired date range.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nif start_date:\n    factors_ff3_monthly_raw = factors_ff3_monthly_raw.filter(\n        pl.col(\"date\") >= pl.lit(start_date).str.to_date()\n    )\nif end_date:\n    factors_ff3_monthly_raw = factors_ff3_monthly_raw.filter(\n        pl.col(\"date\") <= pl.lit(end_date).str.to_date()\n    )\n\nfactors_ff3_monthly = (\n    factors_ff3_monthly_raw.rename(lambda c: c.lower())\n    .rename({\"mkt-rf\": \"mkt_excess\", \"rf\": \"risk_free\"})\n    .with_columns(pl.exclude(\"date\").replace({-99.99: None, -999: None}) / 100)\n    .select(pl.col(\"date\"), pl.exclude(\"date\"))\n)\nfactors_ff3_monthly\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (780, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>date</th><th>mkt_excess</th><th>smb</th><th>hml</th><th>risk_free</th></tr><tr><td>date</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>1960-01-01</td><td>-0.0698</td><td>0.0212</td><td>0.0265</td><td>0.0033</td></tr><tr><td>1960-02-01</td><td>0.0116</td><td>0.006</td><td>-0.0197</td><td>0.0029</td></tr><tr><td>1960-03-01</td><td>-0.0163</td><td>-0.0055</td><td>-0.0275</td><td>0.0035</td></tr><tr><td>1960-04-01</td><td>-0.0171</td><td>0.0022</td><td>-0.0214</td><td>0.0019</td></tr><tr><td>1960-05-01</td><td>0.0312</td><td>0.0129</td><td>-0.0373</td><td>0.0027</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>2024-08-01</td><td>0.016</td><td>-0.035</td><td>-0.011</td><td>0.0048</td></tr><tr><td>2024-09-01</td><td>0.0172</td><td>-0.0012</td><td>-0.0277</td><td>0.004</td></tr><tr><td>2024-10-01</td><td>-0.01</td><td>-0.0096</td><td>0.0089</td><td>0.0039</td></tr><tr><td>2024-11-01</td><td>0.0649</td><td>0.0454</td><td>0.0029</td><td>0.004</td></tr><tr><td>2024-12-01</td><td>-0.0317</td><td>-0.027</td><td>-0.0298</td><td>0.0037</td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n:::\n\nAll of these steps are doable, but none of them are really about finance---they are just the technical scaffolding required before you can work with the actual factor returns. That is where a dedicated package becomes invaluable.\n\n### Using the tidyfinance shortcut\n\nThe `tidyfinance` package performs the entire workflow above under the hood: you request a Fama-French dataset by name and receive a clean, consistently formatted data frame from Kenneth French's data library. This avoids repetitive boilerplate, reduces errors, and lets you focus on modeling rather than data plumbing. For precise descriptions of the variables, we suggest consulting Prof. Kenneth French's finance data library directly. We can use the `download_data()` function to download the same monthly *Fama/French 3 Factors* as above.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff3_monthly <- download_data(\n  domain = \"famafrench\",\n  dataset = \"Fama/French 3 Factors\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\nBecause the downloaded data arrives with timestamp columns, we cast the `date` column to the polars `Date` type — calendar dates rather than timestamps — a convention we use for all tables we store in this book.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_ff3_monthly = pl.from_pandas(\n    tf.download_data(\n        domain=\"famafrench\",\n        dataset=\"Fama/French 3 Factors\",\n        start_date=start_date,\n        end_date=end_date,\n    )\n).with_columns(pl.col(\"date\").cast(pl.Date))\n```\n:::\n\n\n:::\n\nWe also download the set *5 Factors (2x3)*, which additionally includes the return time series of the profitability `rmw` and investment `cma` factors. We demonstrate how the monthly factors are constructed in the chapter [Replicating Fama and French Factors](replicating-fama-and-french-factors.qmd).\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff5_monthly <- download_data(\n  domain = \"famafrench\",\n  dataset = \"Fama/French 5 Factors (2x3)\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_ff5_monthly = pl.from_pandas(\n    tf.download_data(\n        domain=\"famafrench\",\n        dataset=\"Fama/French 5 Factors (2x3)\",\n        start_date=start_date,\n        end_date=end_date,\n    )\n).with_columns(pl.col(\"date\").cast(pl.Date))\n```\n:::\n\n\n:::\n\nIt is straightforward to download the corresponding *daily* Fama-French factors with the same function.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff3_daily <- download_data(\n  domain = \"famafrench\",\n  dataset = \"Fama/French 3 Factors [Daily]\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_ff3_daily = pl.from_pandas(\n    tf.download_data(\n        domain=\"famafrench\",\n        dataset=\"Fama/French 3 Factors [Daily]\",\n        start_date=start_date,\n        end_date=end_date,\n    )\n).with_columns(pl.col(\"date\").cast(pl.Date))\n```\n:::\n\n\n:::\n\nIn a subsequent chapter, we also use the monthly returns of 10 industry portfolios, so let us fetch that data, too.\\index{Data!Industry portfolios}\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindustries_ff_monthly <- download_data(\n  domain = \"famafrench\",\n  dataset = \"10 Industry Portfolios\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nindustries_ff_monthly = pl.from_pandas(\n    tf.download_data(\n        domain=\"famafrench\",\n        dataset=\"10 Industry Portfolios\",\n        start_date=start_date,\n        end_date=end_date,\n    )\n).with_columns(pl.col(\"date\").cast(pl.Date))\n```\n:::\n\n\n:::\n\nIt is worth taking a look at all available portfolio return time series from Kenneth French's homepage.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nYou can list all the Fama-French datasets that `tidyfinance` supports as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist_supported_datasets(domain = \"Fama-French\")\n```\n:::\n\n\n### Python\n\nYou should check out the other sets by calling `tf.get_available_famafrench_datasets()`.\n\n:::\n\n## q-Factors\n\nIn recent years, the academic discourse experienced the rise of alternative factor models, e.g., in the form of the @Hou2015 *q*-factor model. We refer to the [extended background](http://global-q.org/background.html) information provided by the original authors for further information. The *q* factors can be downloaded directly from the authors' homepage.\\index{Data!q-factors}\\index{Factor!q-factors}\n\nWe also need to adjust this data. First, we discard information we will not use in the remainder of the book. Then, we rename the columns with the \"R\\_\"-prescript using regular expressions and write all column names in lowercase. Finally, we apply the same transform of dividing by 100 to all factor returns. You should always try sticking to a consistent style for naming objects, which we try to illustrate here - the emphasis is on *try*. You can check out style guides available online, e.g., [Hadley Wickham's `tidyverse` style guide.](https://style.tidyverse.org/index.html)\\index{Style guide}\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nWe download the CSV from within `read_csv()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_q_monthly_link <-\n  \"https://global-q.org/uploads/1/2/2/6/122679606/q5_factors_monthly_2024.csv\"\n\nfactors_q_monthly <- read_csv(factors_q_monthly_link) |>\n  mutate(date = ymd(str_c(year, month, \"01\", sep = \"-\"))) |>\n  select(-year, -month) |>\n  rename_with(~ str_remove(., \"R_\")) |>\n  rename_with(str_to_lower) |>\n  mutate(across(-date, ~ . / 100)) |>\n  select(date, risk_free = f, mkt_excess = mkt, everything()) |>\n  filter(date >= start_date & date <= end_date)\n```\n:::\n\n\n### Python\n\nWe download the CSV with `requests` and pass the response body directly to `pl.read_csv()`:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_q_monthly_link = (\n    \"https://global-q.org/uploads/1/2/2/6/122679606/q5_factors_monthly_2024.csv\"\n)\n\nfactors_q_monthly = (\n    pl.read_csv(requests.get(factors_q_monthly_link).content)\n    .with_columns(\n        date=pl.date(pl.col(\"year\"), pl.col(\"month\"), 1)\n    )\n    .drop([\"year\", \"month\"])\n    .rename(lambda x: x.replace(\"R_\", \"\").lower())\n    .rename({\"f\": \"risk_free\", \"mkt\": \"mkt_excess\"})\n    .filter(\n        (pl.col(\"date\") >= pl.lit(start_date).str.to_date())\n        & (pl.col(\"date\") <= pl.lit(end_date).str.to_date())\n    )\n    .with_columns(pl.exclude(\"date\") / 100)\n    .select([\"date\", \"risk_free\", \"mkt_excess\", \"me\", \"ia\", \"roe\", \"eg\"])\n)\n```\n:::\n\n\n:::\n\nAgain, you can use the `tidyfinance` package for a shortcut:\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndownload_data(\n  domain = \"factors_q\",\n  dataset = \"q5_factors_monthly_2024\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntf.download_data(\n    domain=\"factors_q\",\n    dataset=\"q5_factors_monthly\",\n    start_date=start_date,\n    end_date=end_date,\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          date  risk_free  mkt_excess        me        ia       roe        eg\n0   1967-01-01   0.003927    0.081852  0.068122 -0.029263  0.018813 -0.025511\n1   1967-02-01   0.003743    0.007557  0.016235 -0.002915  0.035399  0.021792\n2   1967-03-01   0.003693    0.040169  0.019836 -0.016772  0.018417 -0.011192\n3   1967-04-01   0.003344    0.038786 -0.006700 -0.028972  0.010253 -0.016371\n4   1967-05-01   0.003126   -0.042807  0.027457  0.021864  0.005901  0.001191\n..         ...        ...         ...       ...       ...       ...       ...\n691 2024-08-01   0.004419    0.016518 -0.040817  0.004687  0.018369  0.008116\n692 2024-09-01   0.004619    0.016806 -0.011967 -0.000010  0.007408 -0.032810\n693 2024-10-01   0.003907   -0.009701 -0.011261 -0.011676 -0.002314 -0.008335\n694 2024-11-01   0.003955    0.065002  0.043985 -0.049491 -0.015370 -0.021420\n695 2024-12-01   0.003663   -0.031637 -0.051564 -0.003684 -0.021442  0.049624\n\n[696 rows x 7 columns]\n```\n\n\n:::\n:::\n\n\n:::\n\n## Macroeconomic Predictors\n\nOur next data source is a set of macroeconomic variables often used as predictors for the equity premium. @Goyal2008 comprehensively reexamine the performance of variables suggested by the academic literature to be good predictors of the equity premium. The authors host the data on [Amit Goyal's website.](https://sites.google.com/view/agoyal145) The data is an XLSX-file stored on a public Google Drive location and we directly export a CSV file.\\index{Data!Macro predictors}\\index{Google Drive}\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsheet_id <- \"1bM7vCWd3WOt95Sf9qjLPZjoiafgF_8EG\"\nsheet_name <- \"Monthly\"\nmacro_predictors_url <- paste0(\n  \"https://docs.google.com/spreadsheets/d/\",\n  sheet_id,\n  \"/gviz/tq?tqx=out:csv&sheet=\",\n  sheet_name\n)\nmacro_predictors_raw <- read_csv(macro_predictors_url)\n```\n:::\n\n\n### Python\n\nUsually, you need to authenticate if you interact with Google Drive directly in Python. Since the data is stored via a public link, we can proceed without any authentication.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsheet_id = \"1bM7vCWd3WOt95Sf9qjLPZjoiafgF_8EG\"\nsheet_name = \"macro_predictors.xlsx\"\nmacro_predictors_link = (\n    f\"https://docs.google.com/spreadsheets/d/{sheet_id}\"\n    f\"/gviz/tq?tqx=out:csv&sheet={sheet_name}\"\n)\n```\n:::\n\n\n:::\n\nNext, we transform the columns into the variables that we later use:\n\n1.  The dividend price ratio (`dp`), the difference between the log of dividends and the log of prices, where dividends are 12-month moving sums of dividends paid on the S&P 500 index, and prices are monthly averages of daily closing prices [@Campbell1988; @Campbell2006].\n2.  Dividend yield (`dy`), the difference between the log of dividends and the log of lagged prices [@Ball1978].\n3.  Earnings price ratio (`ep`), the difference between the log of earnings and the log of prices, where earnings are 12-month moving sums of earnings on the S&P 500 index [@Campbell1988].\n4.  Dividend payout ratio (`de`), the difference between the log of dividends and the log of earnings [@Lamont1998].\n5.  Stock variance (`svar`), the sum of squared daily returns on the S&P 500 index [@Guo2006].\n6.  Book-to-market ratio (`bm`), the ratio of book value to market value for the Dow Jones Industrial Average [@Kothari1997].\n7.  Net equity expansion (`ntis`), the ratio of 12-month moving sums of net issues by NYSE listed stocks divided by the total end-of-year market capitalization of NYSE stocks [@Campbell2008].\n8.  Treasury bills (`tbl`), the 3-Month Treasury Bill: Secondary Market Rate from the economic research database at the Federal Reserve Bank at St. Louis [@Campbell1987].\n9.  Long-term yield (`lty`), the long-term government bond yield from Ibbotson's Stocks, Bonds, Bills, and Inflation Yearbook [@Goyal2008].\n10. Long-term rate of returns (`ltr`), the long-term government bond returns from Ibbotson's Stocks, Bonds, Bills, and Inflation Yearbook [@Goyal2008].\n11. Term spread (`tms`), the difference between the long-term yield on government bonds and the Treasury bill [@Campbell1987].\n12. Default yield spread (`dfy`), the difference between BAA and AAA-rated corporate bond yields [@Fama1989].\n13. Inflation (`infl`), the Consumer Price Index (All Urban Consumers) from the Bureau of Labor Statistics [@Campbell2004].\n\nFor variable definitions and the required data transformations, you can consult the material on [Amit Goyal's website](https://sites.google.com/view/agoyal145).\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmacro_predictors <- macro_predictors_raw |>\n  mutate(date = ym(yyyymm)) |>\n  mutate(across(where(is.character), as.numeric)) |>\n  mutate(\n    IndexDiv = Index + D12,\n    logret = log(IndexDiv) - log(lag(IndexDiv)),\n    Rfree = log(Rfree + 1),\n    rp_div = lead(logret - Rfree, 1), # Future excess market return\n    dp = log(D12) - log(Index), # Dividend Price ratio\n    dy = log(D12) - log(lag(Index)), # Dividend yield\n    ep = log(E12) - log(Index), # Earnings price ratio\n    de = log(D12) - log(E12), # Dividend payout ratio\n    tms = lty - tbl, # Term spread\n    dfy = BAA - AAA # Default yield spread\n  ) |>\n  select(\n    date,\n    rp_div,\n    dp,\n    dy,\n    ep,\n    de,\n    svar,\n    bm = `b/m`,\n    ntis,\n    tbl,\n    lty,\n    ltr,\n    tms,\n    dfy,\n    infl\n  ) |>\n  filter(date >= start_date & date <= end_date) |>\n  drop_na()\n```\n:::\n\n\n### Python\n\nSome numeric columns in the raw file contain thousands separators (e.g., `4,769.83`), so we read all columns as strings, strip the commas, and cast to floats before the actual transformations. In addition to the predictors, we compute the one-month-ahead excess market return (`rp_div`), which serves as the prediction target for the equity premium predictors.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmacro_predictors = (\n    pl.read_csv(requests.get(macro_predictors_link).content, infer_schema=False)\n    .with_columns(\n        pl.exclude(\"yyyymm\").str.replace_all(\",\", \"\").cast(pl.Float64, strict=False)\n    )\n    .with_columns(index_div=pl.col(\"Index\") + pl.col(\"D12\"))\n    .with_columns(\n        logret=pl.col(\"index_div\").log() - pl.col(\"index_div\").shift(1).log()\n    )\n    .with_columns(\n        date=pl.col(\"yyyymm\").str.to_date(\"%Y%m\"),\n        rp_div=(pl.col(\"logret\") - (pl.col(\"Rfree\") + 1).log()).shift(-1),\n        dp=pl.col(\"D12\").log() - pl.col(\"Index\").log(),\n        dy=pl.col(\"D12\").log() - pl.col(\"Index\").shift(1).log(),\n        ep=pl.col(\"E12\").log() - pl.col(\"Index\").log(),\n        de=pl.col(\"D12\").log() - pl.col(\"E12\").log(),\n        tms=pl.col(\"lty\") - pl.col(\"tbl\"),\n        dfy=pl.col(\"BAA\") - pl.col(\"AAA\"),\n    )\n    .rename({\"b/m\": \"bm\"})\n    .select(\n        [\n            \"date\",\n            \"rp_div\",\n            \"dp\",\n            \"dy\",\n            \"ep\",\n            \"de\",\n            \"svar\",\n            \"bm\",\n            \"ntis\",\n            \"tbl\",\n            \"lty\",\n            \"ltr\",\n            \"tms\",\n            \"dfy\",\n            \"infl\",\n        ]\n    )\n    .filter(\n        (pl.col(\"date\") >= pl.lit(start_date).str.to_date())\n        & (pl.col(\"date\") <= pl.lit(end_date).str.to_date())\n    )\n    .drop_nulls()\n)\n```\n:::\n\n\n:::\n\nTo get the equivalent data through `tidyfinance`, you can call:\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndownload_data(\n  domain = \"macro_predictors\",\n  dataset = \"monthly\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntf.download_data(\n    domain=\"macro_predictors\",\n    dataset=\"monthly\",\n    start_date=start_date,\n    end_date=end_date,\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           date    rp_div        dp        dy  ...     ltr     tms     dfy      infl\n1068 1960-01-01  0.006165 -3.394191 -3.468337  ...  0.0112  0.0006  0.0073 -0.003401\n1069 1960-02-01 -0.015793 -3.383903 -3.374774  ...  0.0204  0.0033  0.0078  0.003413\n1070 1960-03-01 -0.020521 -3.350808 -3.364804  ...  0.0282  0.0080  0.0076  0.000000\n1071 1960-04-01  0.023755 -3.331425 -3.349108  ... -0.0170  0.0103  0.0075  0.003401\n1072 1960-05-01  0.016046 -3.356176 -3.329677  ...  0.0152  0.0088  0.0082  0.000000\n...         ...       ...       ...       ...  ...     ...     ...     ...       ...\n1830 2023-07-01 -0.022065 -4.198545 -4.167881  ... -0.0035 -0.0135  0.0108  0.001908\n1831 2023-08-01 -0.053627 -4.177780 -4.195656  ... -0.0052 -0.0113  0.0107  0.004367\n1832 2023-09-01 -0.026090 -4.124953 -4.174900  ... -0.0221 -0.0094  0.0103  0.002485\n1833 2023-10-01  0.079457 -4.097976 -4.120201  ... -0.0121 -0.0054  0.0102 -0.000383\n1834 2023-11-01  0.038308 -4.178670 -4.093246  ...  0.0347 -0.0077  0.0101 -0.002015\n\n[767 rows x 15 columns]\n```\n\n\n:::\n:::\n\n\n:::\n\n## Other Macroeconomic Data\n\nThe Federal Reserve Bank of St. Louis provides the Federal Reserve Economic Data (FRED), an extensive database for macroeconomic data. In total, there are 817,000 US and international time series from 108 different sources. The data can be downloaded directly from FRED by constructing the appropriate URL. For instance, let us consider the consumer price index (CPI) data that can be found under the [CPIAUCNS](https://fred.stlouisfed.org/series/CPIAUCNS) key.\\index{Data!FRED}\\index{Data!CPI}\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseries <- \"CPIAUCNS\"\nurl <- paste0(\n  \"https://fred.stlouisfed.org/graph/fredgraph.csv?id=\",\n  series\n)\n```\n:::\n\n\nWe can then use the `httr2` [@httr2] package to request the CSV, extract the data from the response body, and convert the columns to a tidy format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresp <- request(url) |>\n  req_perform()\nresp_csv <- resp |>\n  resp_body_string()\n\ncpi_monthly <- resp_csv |>\n  read_csv() |>\n  mutate(\n    date = as.Date(observation_date),\n    value = as.numeric(.data[[series]]),\n    series = series,\n    .keep = \"none\"\n  ) |>\n  filter(date >= start_date & date <= end_date) |>\n  mutate(\n    cpi = value / value[date == max(date)]\n  ) |>\n  select(date, series, value, cpi)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The `file` argument of `vroom()` must use `I()` for literal data as\nof vroom 1.5.0.\n  \n  # Bad:\n  vroom(\"X,Y\\n1.5,2.3\\n\")\n  \n  # Good:\n  vroom(I(\"X,Y\\n1.5,2.3\\n\"))\nℹ The deprecated feature was likely used in the readr package.\n  Please report the issue at\n  <https://github.com/tidyverse/readr/issues>.\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nseries = \"CPIAUCNS\"\nurl = f\"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series}\"\n```\n:::\n\n\nWe can then use the `requests` module to request the CSV, extract the data from the response body, and convert the columns to a tidy format. Note that we pass `impersonate=\"chrome\"` so that the request mimics a regular browser; FRED rejects downloads that do not look like they come from a browser.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nresp = requests.get(url, impersonate=\"chrome\")\n\ncpi_monthly = (\n    pl.read_csv(resp.content)\n    .with_columns(\n        date=pl.col(\"observation_date\").str.to_date(),\n        value=pl.col(series).cast(pl.Float64, strict=False),\n        series=pl.lit(series),\n    )\n    .select([\"date\", \"series\", \"value\"])\n    .filter(\n        (pl.col(\"date\") >= pl.lit(start_date).str.to_date())\n        & (pl.col(\"date\") <= pl.lit(end_date).str.to_date())\n    )\n    .with_columns(cpi=pl.col(\"value\") / pl.col(\"value\").last())\n)\n```\n:::\n\n\n:::\n\nThe last line sets the current (latest) price level as the reference price level.\n\nThe `tidyfinance` package can, of course, also fetch the same index data and many more data series:\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndownload_data(\n  domain = \"fred\",\n  series = \"CPIAUCNS\",\n  start_date = start_date,\n  end_date = end_date\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 780 × 3\n  date       value series  \n  <date>     <dbl> <chr>   \n1 1960-01-01  29.3 CPIAUCNS\n2 1960-02-01  29.4 CPIAUCNS\n3 1960-03-01  29.4 CPIAUCNS\n4 1960-04-01  29.5 CPIAUCNS\n5 1960-05-01  29.5 CPIAUCNS\n# ℹ 775 more rows\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npl.from_pandas(\n    tf.download_data(\n        domain=\"fred\", series=\"CPIAUCNS\", start_date=start_date, end_date=end_date\n    )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (780, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>date</th><th>series</th><th>value</th></tr><tr><td>datetime[ns]</td><td>str</td><td>f64</td></tr></thead><tbody><tr><td>1960-01-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>29.3</td></tr><tr><td>1960-02-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>29.4</td></tr><tr><td>1960-03-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>29.4</td></tr><tr><td>1960-04-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>29.5</td></tr><tr><td>1960-05-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>29.5</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>2024-08-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>314.796</td></tr><tr><td>2024-09-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>315.301</td></tr><tr><td>2024-10-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>315.664</td></tr><tr><td>2024-11-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>315.493</td></tr><tr><td>2024-12-01 00:00:00</td><td>&quot;CPIAUCNS&quot;</td><td>315.605</td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n:::\n\nTo download other time series, we just have to look it up on the FRED website and extract the corresponding key from the address. For instance, the producer price index for gold ores can be found under the [PCU2122212122210](https://fred.stlouisfed.org/series/PCU2122212122210) key.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nIf your desired time series is not supported through `tidyfinance`, we recommend working with the `fredr` package [@fredr]. Note that you need to get an API key to use its functionality. We refer to the package documentation for details.\n\n### Python\n\nIf your desired time series is not supported through `tidyfinance`, we recommend working with the `fredapi` package. Note that you need to get an API key to use its functionality. We refer to the package documentation for details.\n\n:::\n\n## Setting Up a Database\n\nNow that we have downloaded some (freely available) data from the web into the memory of our session, let us store that information for future use. We will use the data stored throughout the following chapters, but you could alternatively implement a different strategy and replace the respective code.\n\nThere are many ways to set up and organize your data, depending on the use case. Storing data as Parquet files creates a universal data format that seamlessly works across different programming languages and platforms. Unlike CSV files that often lose data types when shared between R, Python, Julia, or other languages, Parquet files maintain perfect data integrity regardless of which tool reads them. A dataset saved as Parquet in one language can be opened directly in another, such as Python's pandas or Julia's DataFrames.jl.^[In previous editions of this book, we suggested using SQLite databases. However, Parquet files are more versatile and easier to handle across different programming languages. Should you still prefer using SQLite, you can find the relevant code snippets in a separate blog post.]\n\nParquet files are easily created - the code below is really all there is. You do not need any external software. We will store everything in the `data` subfolder, to retrieve data for all subsequent chapters. The initial part of the code ensures that the directory is created if it does not already exist.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nanoparquet)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'nanoparquet' was built under R version 4.5.3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!dir.exists(\"data\")) {\n  dir.create(\"data\")\n}\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport os\n\nif not os.path.exists(\"data\"):\n    os.makedirs(\"data\")\n```\n:::\n\n\n:::\n\nNext, we create a file with the monthly Fama-French factor data. We do so with the `write_parquet()` function.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_parquet(factors_ff3_monthly, \"data/factors_ff3_monthly.parquet\")\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_ff3_monthly.write_parquet(\"data/factors_ff3_monthly.parquet\")\n```\n:::\n\n\n:::\n\nYou can retrieve the data directly into your memory by calling the corresponding read function.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nThe `read_parquet()` function loads the file into memory as a regular data frame, which we can pipe directly into `dplyr` verbs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_parquet(\"data/factors_ff3_monthly.parquet\") |>\n  select(date, risk_free) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A data frame: 10 × 2\n  date       risk_free\n* <date>         <dbl>\n1 1960-01-01    0.0033\n2 1960-02-01    0.0029\n3 1960-03-01    0.0035\n4 1960-04-01    0.0019\n5 1960-05-01    0.0027\n# ℹ 5 more rows\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npl.read_parquet(\"data/factors_ff3_monthly.parquet\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (780, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>date</th><th>mkt_excess</th><th>smb</th><th>hml</th><th>risk_free</th></tr><tr><td>date</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>1960-01-01</td><td>-0.0698</td><td>0.0212</td><td>0.0265</td><td>0.0033</td></tr><tr><td>1960-02-01</td><td>0.0116</td><td>0.006</td><td>-0.0197</td><td>0.0029</td></tr><tr><td>1960-03-01</td><td>-0.0163</td><td>-0.0055</td><td>-0.0275</td><td>0.0035</td></tr><tr><td>1960-04-01</td><td>-0.0171</td><td>0.0022</td><td>-0.0214</td><td>0.0019</td></tr><tr><td>1960-05-01</td><td>0.0312</td><td>0.0129</td><td>-0.0373</td><td>0.0027</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>2024-08-01</td><td>0.016</td><td>-0.035</td><td>-0.011</td><td>0.0048</td></tr><tr><td>2024-09-01</td><td>0.0172</td><td>-0.0012</td><td>-0.0277</td><td>0.004</td></tr><tr><td>2024-10-01</td><td>-0.01</td><td>-0.0096</td><td>0.0089</td><td>0.0039</td></tr><tr><td>2024-11-01</td><td>0.0649</td><td>0.0454</td><td>0.0029</td><td>0.004</td></tr><tr><td>2024-12-01</td><td>-0.0317</td><td>-0.027</td><td>-0.0298</td><td>0.0037</td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n:::\n\nThe last couple of code chunks are really all there is to organizing a simple database! You can also share the parquet files across devices and programming languages.\n\nBefore we move on to the next data source, let us also store the other tables in our new data folder.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlst(\n  factors_ff5_monthly,\n  factors_ff3_daily,\n  industries_ff_monthly,\n  factors_q_monthly,\n  macro_predictors,\n  cpi_monthly\n) |>\n  iwalk(\\(data, name) write_parquet(data, paste0(\"data/\", name, \".parquet\")))\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndata_dict = {\n    \"factors_ff5_monthly\": factors_ff5_monthly,\n    \"factors_ff3_daily\": factors_ff3_daily,\n    \"industries_ff_monthly\": industries_ff_monthly,\n    \"factors_q_monthly\": factors_q_monthly,\n    \"macro_predictors\": macro_predictors,\n    \"cpi_monthly\": cpi_monthly,\n}\n\nfor key, value in data_dict.items():\n    value.write_parquet(\"data/\" + key + \".parquet\")\n```\n:::\n\n\n:::\n\n## Key Takeaways\n\n- Importing Fama-French factors, q-factors, macroeconomic indicators, and CPI data is simplified through API calls, CSV parsing, and web scraping techniques.\n- The `tidyfinance` package offers pre-processed access to financial datasets, reducing manual data cleaning and saving valuable time.\n- Creating `parquet` files helps manage and organize data efficiently across projects, while maintaining reproducibility.\n- Structured database storage supports scalable data access, which is essential for long-term academic projects and collaborative work in finance.\n\n## Exercises\n\n1.  Download the monthly Fama-French factors manually from [Ken French's data library](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html) and read them in via your language's CSV reader. Validate that you get the same data as via the download script we developed above.\n2.  Download the daily Fama-French 5 factors using `download_data()`. After the successful download and conversion to the column format that we used above, compare the `risk_free`, `mkt_excess`, `smb`, and `hml` columns of `factors_ff3_daily` to `factors_ff5_daily`. Discuss any differences you might find.\n</content>\n</invoke>\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}