---
title: Changelog
metadata:
  pagetitle: Changelog of Tidy Finance with Python
  description-meta: Review all major changes of Tidy Finance with Python since the book publication in 2024 
---

You can find every single change in our [commit history](https://github.com/tidy-finance/website/commits/main). We collect the most important changes for [Tidy Finance with Python](index.qmd) in the list below. 

- [August 4, 2024, Commit e30cff9:](https://github.com/tidy-finance/website/commit/e30cff9f615d3250b502484e66fd5c938deb140c) We switched to `pyfixest` instead of `linearmodels` for fixed effects regressions for better alignment with the R version. 
- [August 4, 2024, Commit 524bdd1:](https://github.com/tidy-finance/website/commit/524bdd1561e72814fa0524a09c3b8b78fb4d3030) We added an additional filter to the Compustat download to exclude non-US companies in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd). 
- [August 1, 2024, Commit 2980cf2:](https://github.com/tidy-finance/website/commit/2980cf2881986862ee6d5a19f5b9cc43cf4ccfef) We updated the data until 2023-12-31 in all chapters.
- [July 29, 2024, Commit cedec3e:](https://github.com/tidy-finance/website/commit/cedec3efda10360da8a44319a199d73e71832467) We removed the `month` column from all chapters because it was misleading and consistently introduced `date`.
- [July 16, 2024, Commit f4bbd00:](https://github.com/tidy-finance/website/commit/f4bbd00bc2ea87fd263c5535a6cf0b25f292fb1d) We improved the documentation with respect to delisting returns in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd). 
 [June 3, 2024, Commit 23d379f:](https://github.com/tidy-finance/website/commit/23d379faa13a05dc9d2bd0a34df583adf408c477) We fixed a bug in [Univaritate Portfolio Sorts](univariate-portfolio-sorts.qmd), which led to wrong annual returns in Figure 3. 
- [May 15, 2024, Commit 2bb2e07:](https://github.com/tidy-finance/website/commit/2bb2e07db91d4c1886d40616fc7cade0df80b67f) We added a new subsection about creating environment variables to [Setting Up Your Environment](setting-up-your-environment.qmd).
- [May 15, 2024, Commit adccfc9:](https://github.com/tidy-finance/website/commit/adccfc93511cfa16f254e13d86a7649b72b996c9) We updated the filters in CRSP download, so that correct historical information is used and daily and monthly data are aligned.
- [April 17, 2024, Commit b8c32aa:](https://github.com/tidy-finance/website/commit/b8c32aae5b4b81724f0ab071ab5035588f75b52f) Corrects a typo in the TRACE download.
- [April 15, 2024, Commit c0f5cc0:](https://github.com/tidy-finance/website/commit/c0f5cc09e00d9ab7f6dfc9eb55f89ed2fc090a02) Fixes the definition of the dividend yield.
