---
pagetitle: "Tidy Finance with Python"
number-sections: false
editor: 
  markdown: 
    wrap: sentence
---

# Preface

::: {.callout-note}
You are reading the work-in-progress edition of **Tidy Finance with Python**. Code chunks and text might change over the next couple of months. We are always looking for feedback via [contact\@tidy-finance.org](mailto:contact@tidy-finance.org). Meanwhile, you can find the complete R version [here](../r/index.qmd).
:::

## Why Does This Book Exist?

Our book [Tidy Finance with R](../r/index.qmd) received great feedback from students and teachers alike. However, one of the most common feedback we received was that many interested coders are constrained and have to use Python in their institutions. We really love R for data analysis tasks, but we acknowledge the flexibility and popularity of Python. Hence, we decided to increase our team of authors with a Python expert and extend our original work following the same tidy principles. 

## Who Should Read This Book?

We write this book for three audiences:

- Students who want to acquire the basic tools required to conduct financial research ranging from undergrad to graduate level. The book’s structure is simple enough such that the material is sufficient for self-study purposes.
- Instructors who look for materials to teach courses in empirical finance or financial economics. We provide plenty of examples and focus on intuitive explanations that can easily be adjusted or expanded. At the end of each chapter, we provide exercises that we hope inspire students to dig deeper.
- Data analysts or statisticians who work on issues dealing with financial data and who need practical tools to succeed.

## What Will You Learn?

The book is divided into five parts:

- The first part helps you to set-up your development environment and introduces you to important concepts around which our approach to Tidy Finance revolves.
- The second part provides tools to organize your data and prepare the most common data sets used in financial research. Although many important data are behind paywalls, we start by describing different open-source data and how to download them. We then move on to prepare two of the most popular datasets in financial research: CRSP and Compustat. We reuse the data from these chapters in all subsequent chapters. 
- The third part deals with key concepts of empirical asset pricing, such as beta estimation, portfolio sorts, performance analysis, and asset pricing regressions.
- In the fourth part, we apply linear models to panel data and machine learning methods to problems in factor selection and option pricing.
- The last part provides approaches for parametric, constrained portfolio optimization, and backtesting procedures.
Each chapter is self-contained and can be read individually. Yet the data chapters provide an important background necessary for data management in all other chapters.

## What Won't You Learn?

This book is about empirical work. While we assume only basic knowledge of statistics and econometrics, we do not provide detailed treatments of the underlying theoretical models or methods applied in this book. Instead, you find references to the seminal academic work in journal articles or textbooks for more detailed treatments. We believe that our comparative advantage is to provide a thorough implementation of typical approaches such as portfolio sorts, backtesting procedures, regressions, machine learning methods, or other related topics in empirical finance. We enrich our implementations by discussing the nitty-gritty choices you face while conducting empirical analyses. We hence refrain from deriving theoretical models or extensively discussing the statistical properties of well-established tools.

## Why Python?

Python [@python] is the leading programming language for data science and widely used in financial applications. 

## Why Tidy?

As you start working with data, you quickly realize that you spend a lot of time reading, cleaning, and transforming your data. In fact, it is often said that more than 80% of data analysis is spent on preparing data.
By *tidying data*, we want to structure data sets to facilitate further analyses.
As @Wickham2014 puts it:

> \[T\]idy datasets are all alike, but every messy dataset is messy in its own way.
> Tidy datasets provide a standardized way to link the structure of a dataset (its physical layout) with its semantics (its meaning).

In its essence, tidy data follows these three principles:

1.  Every column is a variable.
2.  Every row is an observation.
3.  Every cell is a single value.

Throughout this book, we try to follow these principles as best as possible.
If you want to learn more about tidy data principles in an informal manner, we refer you to [this vignette](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html) as part of @tidyr.

In addition to the data layer, there are also tidy coding principles outlined in [the tidy tools manifesto](https://tidyverse.tidyverse.org/articles/manifesto.html) that we try to follow:

1.  Reuse existing data structures.
2.  Compose simple functions with the pipe.
3.  Embrace functional programming.
4.  Design for humans.

## About the Authors

- [Christoph Frey](https://sites.google.com/site/christophfrey/) is a Quantitative Researcher at [Pinechip Capital GmbH](https://www.pinechip.capital/landingtile/index.html) and Research Fellow at the [Centre for Financial Econometrics, Asset Markets and Macroeconomic Policy](https://www.lancaster.ac.uk/lums/research/areas-of-expertise/centre-for-financial-econometrics-asset-markets-and-macroeconomic-policy/) at Lancaster University. He published research on Bayesian Econometrics and previously worked as an Assistant Professor at the [Erasmus Universiteit Rotterdam](https://www.eur.nl/). 
- [Christoph Scheuch](https://christophscheuch.github.io/) is the Director of Product at the social trading platform [wikifolio.com.](https://www.wikifolio.com/) He is responsible for product planning, execution, and monitoring and manages a team of data scientists to analyze user behavior and develop data-driven products. Christoph is also an external lecturer at the Vienna University of Economics and Business, where he teaches finance students how to manage empirical projects.
- [Stefan Voigt](https://voigtstefan.me/) is an Assistant Professor of Finance at the [Department of Economics at the University in Copenhagen](https://www.economics.ku.dk/) and a research fellow at the [Danish Finance Institute.](https://danishfinanceinstitute.dk/) His research focuses on blockchain technology, high-frequency trading, and financial econometrics. Stefan's research has been published in the leading finance and econometrics journals. He received the Danish Finance Institute Teaching Award 2022 for his courses for students and practitioners on empirical finance based on this book.
- [Patrick Weiss](https://sites.google.com/view/patrick-weiss) is an Assistant Professor of Finance at [Reykjavik University](https://en.ru.is) and an external lecturer at the [Vienna University of Economics and Business.](https://www.wu.ac.at/en/) His research activity centers around the intersection of empirical asset pricing and corporate finance. Patrick is especially passionate about empirical asset pricing and has published research in leading journals in financial economics.

## License

This book is licensed to you under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
The code samples in this book are licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0), i.e., public domain](https://creativecommons.org/publicdomain/zero/1.0/).
You can cite this work-in-progress version of the python project as follows:

> Frey, C., Scheuch, C., Voigt, S., & Weiss, P. (2023).
> Tidy Finance with Python.
> <https://www.tidy-finance.org>

``` bibtex
@book{Frey2023,
  title = {Tidy Finance with Python},
  author = {Frey, Christoph and Scheuch, Christoph and Voigt, Stefan and Weiss, Patrick},
  year = {2023},
  edition = {work-in-progress},
  url = {https://tidy-finance.org}
}
```
