---
title: TRACE and FISD
metadata:
    pagetitle: TRACE and FISD with Python
    description-meta: Download and prepare corporate bond data such as TRACE and FISD from WRDS using the programming language Python. 
---

```{python}
#| label: trace-and-fisd-setup
#| echo: false
exec(open("python/render-settings.py").read())
```

::: callout-note
You are reading **Tidy Finance with Python**. You can find the equivalent chapter for the sibling **Tidy Finance with R** [here](../r/trace-and-fisd.qmd).
:::

In this chapter, we dive into the US corporate bond market. Bond markets are far more diverse than stock markets, as most issuers have multiple bonds outstanding simultaneously with potentially very different indentures. This market segment is exciting due to its size (roughly ten trillion USD outstanding), heterogeneity of issuers (as opposed to government bonds), market structure (mostly over-the-counter trades), and data availability. We introduce how to use bond characteristics from FISD and trade reports from TRACE and provide code to download and clean TRACE in Python.

Many researchers study liquidity in the US corporate bond market, with notable contributions from @bessembinder2006, @Edwards2007, and @Ohara2021, among many others. We do not cover bond returns here, but you can compute them from TRACE data. Instead, we refer to studies on the topic such as @Bessembinder2008, @bai2019, and @kelly2020 and a survey by @Huang2021. 

This chapter also draws on the resources provided by the project [Open Source Bond Asset Pricing](https://openbondassetpricing.com/) and their related publication, i.e., @Dickerson2023. We encourage you to visit their website to check out the additional resources they provide. Moreover, WRDS provides bond returns computed from TRACE data at a monthly frequency.\index{Corporate bonds}

The current chapter relies on the following set of Python packages. 

```{python}
#| label: trace-and-fisd-packages
import polars as pl
import numpy as np
import tidyfinance as tf
import httpimport
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds

from datetime import date
from plotnine import *
from sqlalchemy import create_engine
from mizani.formatters import comma_format
```

```{python}
#| label: trace-and-fisd-render-plotnine
#| echo: false
exec(open("python/render-plotnine-custom.py").read())
```

Compared to previous chapters, we load `httpimport` [@httpimport] to source code provided in the public [Gist.](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) Note that you should be careful with loading anything from the web via this method, and it is highly discouraged to use any unsecured "HTTP" links. Also, you might encounter a problem when using this from a corporate computer that prevents downloading data through a firewall.

## Bond Data from WRDS 

Both bond databases we need are available on [WRDS](https://wrds-www.wharton.upenn.edu/) to which we establish the PostgreSQL connection described in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd).\index{WRDS}

```{python}
#| label: trace-and-fisd-wrds-connection
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, URL

load_dotenv()

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=os.getenv("WRDS_USER"),
    password=os.getenv("WRDS_PASSWORD"),
    host="wrds-pgdata.wharton.upenn.edu",
    port=9737,
    database="wrds",
)

wrds = create_engine(connection_url, pool_pre_ping=True)
```

## Mergent FISD

For research on US corporate bonds, the Mergent Fixed Income Securities Database (FISD) is the primary resource for bond characteristics.\index{Data!FISD} There is a [detailed manual](https://wrds-www.wharton.upenn.edu/documents/1364/FixedIncome_Securities_Master_Database_User_Guide_v4.pdf) on WRDS, so we only cover the necessary subjects here. FISD data comes in two main variants, namely, centered on issuers or issues. In either case, the most useful identifiers are [CUSIPs.](https://www.cusip.com/index.html) 9-digit CUSIPs identify securities issued by issuers. The issuers can be identified from the first six digits of a security CUSIP, which is also called a 6-digit CUSIP. Both stocks and bonds have CUSIPs.\index{CUSIP} This connection would, in principle, allow matching them easily, but due to changing issuer details, this approach only yields small coverage.

We use the issue-centered version of FISD to identify the subset of US corporate bonds that meet the standard criteria [@bessembinder2006]. The WRDS table `fisd_mergedissue` contains most of the information we need on a 9-digit CUSIP level. Due to the diversity of corporate bonds, details in the indenture vary significantly. We focus on common bonds that make up the majority of trading volume in this market without diverging too much in indentures. 

The following chunk connects to the data and selects the bond sample to remove certain bond types that are less commonly used [see, e.g., @Dick2012; @Ohara2021, among many others]. In particular, we use the filters listed below. Note that we also treat missing values in these flags.

1. Keep only senior bonds (`security_level = 'SEN'`).
1. Exclude bonds which are secured lease obligations (`slob = 'N' OR slob IS NULL`).
1. Exclude secured bonds (`security_pledge IS NULL`).
1. Exclude asset-backed bonds (`asset_backed = 'N' OR asset_backed IS NULL`).
1. Exclude defeased bonds (`(defeased = 'N' OR defeased IS NULL) AND defeased_date IS NULL`).
1. Keep only the bond types US Corporate Debentures (`'CDEB'`), US Corporate Medium Term Notes (`'CMTN'`), US Corporate Zero Coupon Notes and Bonds (`'CMTZ'`, `'CZ'`), and US Corporate Bank Note (`'USBN'`).
1. Exclude bonds that are payable in kind (`(pay_in_kind != 'Y' OR pay_in_kind IS NULL) AND pay_in_kind_exp_date IS NULL`).
1. Exclude foreign (`yankee == "N" OR is.na(yankee)`) and Canadian issuers (`canadian = 'N' OR canadian IS NULL`). 
1. Exclude bonds denominated in foreign currency (`foreign_currency = 'N'`).
1. Keep only fixed (`F`) and zero (`Z`) coupon bonds with additional requirements of `fix_frequency IS NULL`, `coupon_change_indicator = 'N'` and an interest frequency of zero (for zero-coupon bonds), annual, semi-annual, quarterly, or monthly.
1. Exclude bonds that were issued under SEC Rule 144A (`rule_144a = 'N'`).
1. Exclude privately placed bonds (`private_placement = 'N' OR private_placement IS NULL`).
1. Exclude defaulted bonds (`defaulted = 'N' AND filing_date IS NULL AND settlement IS NULL`).
1. Exclude convertible (`convertible = 'N'`), putable (`putable = 'N' OR putable IS NULL`), exchangeable (`exchangeable = 'N' OR exchangeable IS NULL`), perpetual (`perpetual = 'N'`), or preferred bonds (`preferred_security = 'N' OR preferred_security IS NULL`).
1. Exclude unit deal bonds (`(unit_deal = 'N' OR unit_deal IS NULL)`).

```{python}
#| label: trace-and-fisd-fisd-query
fisd_query = (
  "SELECT complete_cusip, maturity, offering_amt, offering_date, "
         "dated_date, interest_frequency, coupon, last_interest_date, "
         "issue_id, issuer_id "
    "FROM fisd.fisd_mergedissue "
    "WHERE security_level = 'SEN' "
          "AND (slob = 'N' OR slob IS NULL) "
          "AND security_pledge IS NULL "              
          "AND (asset_backed = 'N' OR asset_backed IS NULL) "
          "AND (defeased = 'N' OR defeased IS NULL) "
          "AND defeased_date IS NULL "
          "AND bond_type IN ('CDEB', 'CMTN', 'CMTZ', 'CZ', 'USBN') "
          "AND (pay_in_kind != 'Y' OR pay_in_kind IS NULL) "
          "AND pay_in_kind_exp_date IS NULL "
          "AND (yankee = 'N' OR yankee IS NULL) "
          "AND (canadian = 'N' OR canadian IS NULL) "
          "AND foreign_currency = 'N' "
          "AND coupon_type IN ('F', 'Z') "
          "AND fix_frequency IS NULL "
          "AND coupon_change_indicator = 'N' "
          "AND interest_frequency IN ('0', '1', '2', '4', '12') "
          "AND rule_144a = 'N' "
          "AND (private_placement = 'N' OR private_placement IS NULL) "
          "AND defaulted = 'N' "
          "AND filing_date IS NULL "
          "AND settlement IS NULL "
          "AND convertible = 'N' "
          "AND exchange IS NULL "
          "AND (putable = 'N' OR putable IS NULL) "
          "AND (unit_deal = 'N' OR unit_deal IS NULL) "
          "AND (exchangeable = 'N' OR exchangeable IS NULL) "
          "AND perpetual = 'N' "
          "AND (preferred_security = 'N' OR preferred_security IS NULL)"
)

fisd = pl.read_database(
    query=fisd_query,
    connection=wrds,
    schema_overrides={"complete_cusip": pl.String,
                      "interest_frequency": pl.String,
                      "issue_id": pl.Int64, "issuer_id": pl.Int64},
)
```

We also pull issuer information from `fisd_mergedissuer` regarding the industry and country of the firm that issued a particular bond. Then, we filter to include only US-domiciled firms' bonds. We match the data by `issuer_id`.

```{python}
#| label: trace-and-fisd-fisd-issuer
fisd_issuer_query = (
    "SELECT issuer_id, sic_code, country_domicile "
        "FROM fisd.fisd_mergedissuer"
)

fisd_issuer = pl.read_database(
    query=fisd_issuer_query,
    connection=wrds,
    schema_overrides={"issuer_id": pl.Int64, "sic_code": pl.String,
                      "country_domicile": pl.String},
)

fisd = (fisd
    .join(fisd_issuer, how="inner", on="issuer_id")
    .filter(pl.col("country_domicile") == "USA")
    .drop("country_domicile")
)
```

To download the FISD data with the above filters and processing steps, you can use the `tidyfinance` package. Note that you might have to set the login credentials for WRDS first using `tf.set_wrds_credentials()`.

```{python}
#| label: trace-and-fisd-download-fisd
#| output: false
#| eval: false
fisd = pl.from_pandas(tf.download_data(domain="wrds", dataset="fisd"))
```

Finally, we save the bond characteristics to our local folder. This selection of bonds also constitutes the sample for which we will collect trade reports from TRACE below.

```{python}
#| label: trace-and-fisd-write-fisd
#| output: false
fisd.write_parquet("data-python/fisd.parquet")
```

The FISD database also contains other data. The issue-based file contains information on covenants, i.e., restrictions included in bond indentures to limit specific actions by firms [e.g., @handler2021]. The FISD redemption database also contains information on callable bonds. Moreover, FISD also provides information on bond ratings. We do not need either here.

```{python}
#| label: trace-and-fisd-read-fisd
#| echo: false
#| eval: true
fisd = pl.read_parquet("data-python/fisd.parquet")
```

## TRACE

The Financial Industry Regulatory Authority (FINRA) provides the Trade Reporting and Compliance Engine (TRACE).\index{Data!TRACE} In TRACE, dealers that trade corporate bonds must report such trades individually. Hence, we observe trade messages in TRACE that contain information on the bond traded, the trade time, price, and volume. TRACE comes in two variants: standard and enhanced TRACE. We show how to download and clean enhanced TRACE as it contains uncapped volume, a crucial quantity missing in the standard distribution. Moreover, enhanced TRACE also provides information on the respective parties' roles and the direction of the trade report. These items become essential in cleaning the messages.

Why do we repeatedly talk about cleaning TRACE? Trade messages are submitted within a short time window after a trade is executed (less than 15 minutes). These messages can contain errors, and the reporters subsequently correct them or they cancel a trade altogether. The cleaning needs are described by @Dick2009 in detail, and @Dick2014 shows how to clean the enhanced TRACE data using SAS. We do not go into the cleaning steps here, since the code is lengthy and is not our focus here. However, downloading and cleaning enhanced TRACE data is straightforward with our setup.

We store code for cleaning enhanced TRACE with Python on the following GitHub [Gist.](https://gist.githubusercontent.com/patrick-weiss/86ddef6de978fbdfb22609a7840b5d8b) \index{GitHub!Gist} [Clean Enhanced TRACE with Python](clean-enhanced-trace-with-python.qmd) also contains the code for reference. We only need to source the code from the Gist, which we can do with the code below using `httpimport`. In the chunk, we explicitly load the necessary function interpreting the Gist as a module (i.e., you could also use it as a module and precede the function calls with the module's name). Alternatively, you can also go to the Gist, download it, and manually execute it. The `clean_enhanced_trace()` function takes a vector of CUSIPs, a connection to WRDS explained in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd), and a start and end date, respectively. 

```{python}
#| label: trace-and-fisd-source-cleaning
#| warning: false
import requests

url = (
    "https://gist.githubusercontent.com/patrick-weiss/"
    "86ddef6de978fbdfb22609a7840b5d8b/raw/"
    "8fbcc6c6f40f537cd3cd37368be4487d73569c6b/"
)

response = requests.get(url, verify=False)
exec(response.text)
```

The TRACE database is considerably large. Therefore, we only download subsets of data at once. Specifying too many CUSIPs over a long time horizon will result in very long download times and a potential failure due to the size of the request to WRDS. The size limit depends on many parameters, and we cannot give you a guideline here. For the applications in this book, we need data around the Paris Agreement in December 2015 and download the data in sets of 1,000 bonds, which we define below.\index{Paris (Climate) Agreement}

```{python}
#| label: trace-and-fisd-define-batches
cusips = fisd["complete_cusip"].unique().to_list()
batch_size = 1000
batches = np.ceil(len(cusips)/batch_size).astype(int)
```

Finally, we run a loop in the same style as in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd) where we download daily returns from CRSP. For each of the CUSIP sets defined above, we call the cleaning function and save the resulting output. We add new data to the existing dataset for batch two and all following batches.  Because our later applications load the entire table at once, we partition the data by batch rather than by security identifier. Using a smaller number of larger files improves efficiency when loading the full dataset into memory.

```{python}
#| label: trace-and-fisd-download-loop
#| output: false
for j in range(1, batches + 1):
  
    cusip_batch = cusips[
            ((j-1)*batch_size):(min(j*batch_size, len(cusips)))
    ]
    
    cusip_batch_formatted = ", ".join(f"'{cusip}'" for cusip in cusip_batch)
    cusip_string = f"({cusip_batch_formatted})"

    trace_enhanced_sub = pl.from_pandas(clean_enhanced_trace(
            cusips=cusip_string,
            connection=wrds,
            start_date="'01/01/2014'",
            end_date="'11/30/2016'"
    ))
    
    if not trace_enhanced_sub.is_empty():
            table = (trace_enhanced_sub.to_arrow()
                .append_column("batch", pa.array([j] * len(trace_enhanced_sub)))
            )
            pq.write_to_dataset(
                table,
                root_path="data-python/trace_enhanced",
                partition_cols=["batch"],
                existing_data_behavior="overwrite_or_ignore"
            )
        
    print(f"Batch {j} out of {batches} done ({(j/batches)*100:.2f}%)\n")
```

If you want to download the prepared enhanced TRACE data for selected bonds via the `tidyfinance` package, you can call, e.g.:

```{python}
#| label: trace-and-fisd-download-tidyfinance
#| output: false
#| eval: false
tf.download_data(
    domain="wrds",
    dataset="trace_enhanced",
    cusips=["00101JAH9"],
    start_date="2019-01-01", 
    end_date="2021-12-31"
)
```

## Insights into Corporate Bonds

While many news outlets readily provide information on stocks and the underlying firms, corporate bonds are not covered frequently. Additionally, the TRACE database contains trade-level information, potentially new to students. Therefore, we provide you with some insights by showing some summary statistics.\index{Summary statistics}

We start by looking into the number of bonds outstanding over time and compare it to the number of bonds traded in our sample. First, we compute the number of bonds outstanding for each quarter around the Paris Agreement from 2014 to 2016. 

```{python}
#| label: trace-and-fisd-bonds-outstanding
dates = pl.DataFrame(
    {"date": pl.date_range(
        date(2014, 3, 1), date(2016, 11, 30), interval="3mo", eager=True
    ).dt.month_end()}
)

bonds_outstanding = (dates
    .join(fisd.select(["complete_cusip", "offering_date", "maturity"]), how="cross")
    .filter(
        (pl.col("date") >= pl.col("offering_date"))
        & (pl.col("date") <= pl.col("maturity"))
    )
    .group_by("date")
    .agg(count=pl.len())
    .with_columns(type=pl.lit("Outstanding"))
)
```

Next, we look at the bonds traded each quarter in the same period. Notice that we load the complete TRACE data from our dataset, as we only have a single part of it in the environment from the download loop above.

```{python}
#| label: trace-and-fisd-bonds-traded
trace_enhanced = pl.from_arrow(
    ds.dataset("data-python/trace_enhanced", format="parquet").to_table()
)

bonds_traded = (trace_enhanced
    .with_columns(
        date=pl.when(pl.col("trd_exctn_dt").dt.day() == 1)
            .then(pl.col("trd_exctn_dt").dt.offset_by("-1mo"))
            .otherwise(pl.col("trd_exctn_dt").dt.truncate("1mo"))
            .dt.truncate("1q")
            .cast(pl.Date)
    )
    .group_by("date")
    .agg(count=pl.col("cusip_id").n_unique())
    .with_columns(type=pl.lit("Traded"))
)
```

Finally, we plot the two time series in @fig-401.

```{python}
#| label: fig-401
#| fig-cap: "Number of corporate bonds outstanding each quarter as reported by Mergent FISD and the number of traded bonds from enhanced TRACE between 2014 and end of 2016."
#| fig-alt: "Title: Number of bonds outstanding and traded each quarter. The figure shows a time series of outstanding bonds and bonds traded. The amount outstanding increases monotonically between 2014 and 2016. The number of bonds traded represents only a fraction of roughly 60 percent, which peaks around the third quarter of 2016."
#| fig-pos: "htb"
bonds_combined = pl.concat(
    [
        bonds_outstanding.select(["date", "count", "type"]),
        bonds_traded.select(["date", "count", "type"])
    ]
).sort("date")

bonds_figure = (
    ggplot(
        bonds_combined,
        aes(x="date", y="count", color="type", linetype="type")
    )
    + geom_line()
    + labs(
        x="", y="", color="", linetype="",
        title="Number of bonds outstanding and traded each quarter"
        )
    + scale_x_date(date_breaks="1 year", date_labels="%Y")
    + scale_y_continuous(labels=comma_format())
)
bonds_figure.draw()
```

We see that the number of bonds outstanding increases steadily between 2014 and 2016. During our sample period of trade data, we see that the fraction of bonds trading each quarter is roughly 60 percent. The relatively small number of traded bonds means that many bonds do not trade through an entire quarter. This lack of trading activity illustrates the generally low level of liquidity in the corporate bond market, where it can be hard to trade specific bonds. Does this lack of liquidity mean that corporate bond markets are irrelevant in terms of their size? With over 7,500 traded bonds each quarter, it is hard to say that the market is small. However, let us also investigate the characteristics of issued corporate bonds. In particular, we consider maturity (in years), coupon, and offering amount (in million USD).\index{Liquidity}

```{python}
#| label: trace-and-fisd-bond-characteristics
average_characteristics = (fisd
    .with_columns(
        maturity=(pl.col("maturity") - pl.col("offering_date")).dt.total_days()/365,
        offering_amt=pl.col("offering_amt")/10**3
    )
    .unpivot(
        on=["maturity", "coupon", "offering_amt"],
        variable_name="measure", value_name="value"
    )
    .drop_nulls()
    .group_by("measure")
    .agg(
        mean=pl.col("value").mean(),
        std=pl.col("value").std(),
        min=pl.col("value").min(),
        q05=pl.col("value").quantile(0.05),
        median=pl.col("value").quantile(0.50),
        q95=pl.col("value").quantile(0.95),
        max=pl.col("value").max(),
    )
)
average_characteristics.with_columns(pl.col(pl.Float64).round(2))
```

We see that the sample is dominated by zero-coupon bonds: the median coupon is zero, and even the average coupon is only around 2 percent. The distributions of offering amount and maturity are strongly right-skewed. The median bond is small and short-dated, with an offering amount below 3 million USD and a maturity of around three and a half years, while the averages are pulled up to over 120 million USD and roughly five and a half years, respectively, by a tail of large, long-dated issues.

Finally, let us compute some summary statistics for the trades in this market. To this end, we show a summary based on aggregate information daily. In particular, we consider the trade size (in million USD) and the number of trades.

```{python}
#| label: trace-and-fisd-trade-summary
average_trade_size = (trace_enhanced
    .group_by("trd_exctn_dt")
    .agg(
        trade_size=(pl.col("entrd_vol_qt")*pl.col("rptd_pr")/100).sum()/10**6,
        trade_number=pl.len()
    )
    .unpivot(
        index=["trd_exctn_dt"],
        on=["trade_size", "trade_number"],
        variable_name="measure", value_name="value"
    )
    .group_by("measure")
    .agg(
        mean=pl.col("value").mean(),
        std=pl.col("value").std(),
        min=pl.col("value").min(),
        q05=pl.col("value").quantile(0.05),
        median=pl.col("value").quantile(0.50),
        q95=pl.col("value").quantile(0.95),
        max=pl.col("value").max(),
    )
)
average_trade_size.with_columns(pl.col(pl.Float64).round(0))
```

On average, around 13 billion USD of corporate bonds are traded daily in nearly 26,000 transactions. We can, hence, conclude that the corporate bond market is indeed significant in terms of trading volume and activity.

## Key Takeaways

- The US corporate bond market is large, diverse, and primarily trades over-the-counter, making it an important yet complex subject of financial research.
- The Mergent FISD database on WRDS provides detailed bond characteristics, which are essential for selecting a representative sample of US corporate bonds.
- Enhanced TRACE data includes uncapped trade volumes and dealer roles, offering valuable insights into bond market liquidity and trade execution.
- Cleaning TRACE data is crucial, as trades may be corrected or canceled shortly after reporting, but automated functions in the `tidyfinance` Python package simplify this task.

## Exercises

1. Compute the amount outstanding across all bonds over time. Make sure to subtract all matured bonds. How would you describe the resulting plot?
1. Compute the number of days each bond is traded (accounting for the bonds' maturities and issuances). Start by looking at the number of bonds traded each day in a graph similar to the one above. How many bonds trade on more than 75 percent of trading days? 
1. WRDS provides more information from Mergent FISD such as ratings in the table `fisd_ratings`. Download the ratings table and plot the distribution of ratings for the different rating providers. How would you map the different providers to a common numeric rating scale? \index{Rating}
