{
  "hash": "da5ace3a6b142c9d3368e40ae8195e86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Factor Selection via Machine Learning\naliases:\n  - ../factor-selection-via-machine-learning.html\n  - ../r/factor-selection-via-machine-learning.html\n  - ../python/factor-selection-via-machine-learning.html\nmetadata:\n  pagetitle: Factor Selection via Machine Learning\n  description-meta: Use machine learning tools such as Lasso and Ridge regressions to identify asset pricing factors using the programming languages R and Python.\n---\n\n\n::: {.cell}\n\n:::\n\n\nThe aim of this chapter is twofold. From a data science perspective, we introduce tools for modeling and machine learning (ML). From a finance perspective, we address the notion of *factor zoo* [@Cochrane2011] using ML methods. We introduce Lasso and Ridge regression as a special case of penalized regression models. Then, we explain the concept of cross-validation for model *tuning* with Elastic Net regularization as a popular example. We implement and showcase the entire cycle from model specification, training, and forecast evaluation. While the tools can generally be applied to an abundance of interesting asset pricing problems, we apply penalized regressions for identifying macroeconomic variables and asset pricing factors that help explain a cross-section of industry portfolios.\\index{Machine learning}\n\nIn previous chapters, we illustrate that stock characteristics such as size provide valuable pricing information in addition to the market beta.\\index{Factor zoo}\\index{Factor model}\\index{CAPM} Such findings question the usefulness of the Capital Asset Pricing Model. In fact, during the last decades, financial economists discovered a plethora of additional factors which may be correlated with the marginal utility of consumption (and would thus deserve a prominent role in pricing applications). The search for factors that explain the cross-section of expected stock returns has produced hundreds of potential candidates, as noted more recently by @Harvey2016, @Mclean2016, and @Hou2020. Therefore, given the multitude of proposed risk factors, the challenge these days rather is: *do we believe in the relevance of 300+ risk factors?* During recent years, promising methods from the field of ML got applied to common finance applications. We refer to @Mullainathan2017 for a treatment of ML from the perspective of an econometrician, @Nagel2021 for an excellent review of ML practices in asset pricing, @Easley2021 for ML applications in (high-frequency) market microstructure, and @Dixon2020 for a detailed treatment of all methodological aspects.\n\n## Brief Theoretical Background\n\nThis is a book about *doing* empirical work in a tidy manner, and we refer to any of the many excellent textbook treatments of ML methods and especially penalized regressions for some deeper discussion. Excellent material is provided, for instance, by @Hastie2009, @Hastie2013, and @DePrado2018. Instead, we briefly summarize the idea of Lasso and Ridge regressions as well as the more general Elastic Net. Then, we turn to the fascinating question on *how* to implement, tune, and use such models.\n\nTo set the stage, we start with the definition of a linear model: suppose we have data $(y_t, x_t), t = 1,\\ldots, T$, where $x_t$ is a $(K \\times 1)$ vector of regressors and $y_t$ is the response for observation $t$.\nThe linear model takes the form $y_t = \\beta' x_t + \\varepsilon_t$ with some error term $\\varepsilon_t$ and has been studied in abundance. The well-known ordinary-least square (OLS) estimator for the $(K \\times 1)$ vector $\\beta$ minimizes the sum of squared residuals and is then $$\\hat{\\beta}^\\text{ols} = \\left(\\sum\\limits_{t=1}^T x_t'x_t\\right)^{-1} \\sum\\limits_{t=1}^T x_t'y_t.$$\n\\index{Regression!OLS}\n\nWhile we are often interested in the estimated coefficient vector $\\hat\\beta^\\text{ols}$, ML is about the predictive performance most of the time. For a new observation $\\tilde{x}_t$, the linear model generates predictions such that $$\\hat y_t = E\\left(y|x_t = \\tilde x_t\\right) = \\hat\\beta^\\text{ols}{}' \\tilde x_t.$$\nIs this the best we can do?\nNot really: instead of minimizing the sum of squared residuals, penalized linear models can improve predictive performance by choosing other estimators $\\hat{\\beta}$ with lower variance than the estimator $\\hat\\beta^\\text{ols}$.\nAt the same time, it seems appealing to restrict the set of regressors to a few meaningful ones, if possible. In other words, if $K$ is large (such as for the number of proposed factors in the asset pricing literature), it may be a desirable feature to *select* reasonable factors and set $\\hat\\beta^{\\text{ols}}_k = 0$ for some redundant factors.\n\nIt should be clear that the promised benefits of penalized regressions, i.e., reducing the mean squared error (MSE), come at a cost. In most cases, reducing the variance of the estimator introduces a bias such that $E\\left(\\hat\\beta\\right) \\neq \\beta$. What is the effect of such a bias-variance trade-off? To understand the implications, assume the following data-generating process for $y$: $$y = f(x) + \\varepsilon, \\quad \\varepsilon \\sim (0, \\sigma_\\varepsilon^2)$$ We want to recover $f(x)$, which denotes some unknown functional which maps the relationship between $x$ and $y$. While the properties of $\\hat\\beta^\\text{ols}$ as an unbiased estimator may be desirable under some circumstances, they are certainly not if we consider predictive accuracy. Alternative predictors $\\hat{f}(x)$ could be more desirable: For instance, the MSE depends on our model choice as follows: \\index{MSE} $$\\begin{aligned}\nMSE &=E((y-\\hat{f}(x))^2)=E((f(x)+\\epsilon-\\hat{f}(x))^2)\\\\\n&= \\underbrace{E((f(x)-\\hat{f}(x))^2)}_{\\text{total quadratic error}}+\\underbrace{E(\\epsilon^2)}_{\\text{irreducible error}} \\\\\n&= E\\left(\\hat{f}(x)^2\\right)+E\\left(f(x)^2\\right)-2E\\left(f(x)\\hat{f}(x)\\right)+\\sigma_\\varepsilon^2\\\\\n&=E\\left(\\hat{f}(x)^2\\right)+f(x)^2-2f(x)E\\left(\\hat{f}(x)\\right)+\\sigma_\\varepsilon^2\\\\\n&=\\underbrace{\\text{Var}\\left(\\hat{f}(x)\\right)}_{\\text{variance of model}}+ \\underbrace{\\left(E(f(x)-\\hat{f}(x))\\right)^2}_{\\text{squared bias}} +\\sigma_\\varepsilon^2.\n\\end{aligned}$$ While no model can reduce $\\sigma_\\varepsilon^2$, a biased estimator with small variance may have a lower MSE than an unbiased estimator.\n\n### Ridge regression\n\n\\index{Regression!Ridge}\n\nOne biased estimator is known as Ridge regression. @Hoerl1970 propose to minimize the sum of squared errors *while simultaneously imposing a penalty on the $L_2$ norm of the parameters* $\\hat\\beta$. Formally, this means that for a penalty factor $\\lambda\\geq 0$, the minimization problem takes the form $\\min_\\beta \\left(y - X\\beta\\right)'\\left(y - X\\beta\\right)\\text{ s.t. } \\beta'\\beta \\leq c$. Here $c\\geq 0$ is a constant that depends on the choice of $\\lambda$. The larger $\\lambda$, the smaller $c$ (technically speaking, there is a one-to-one relationship between $\\lambda$, which corresponds to the Lagrangian of the minimization problem above and $c$). Here, $X = \\left(x_1  \\ldots  x_T\\right)'$ and $y = \\left(y_1, \\ldots, y_T\\right)'$. A closed-form solution for the resulting regression coefficient vector $\\beta^\\text{ridge}$ exists: $$\\hat{\\beta}^\\text{ridge} = \\left(X'X + \\lambda I\\right)^{-1}X'y.$$ A couple of observations are worth noting: $\\hat\\beta^\\text{ridge} = \\hat\\beta^\\text{ols}$ for $\\lambda = 0$ and $\\hat\\beta^\\text{ridge} \\rightarrow 0$ for $\\lambda\\rightarrow \\infty$. Also for $\\lambda > 0$, $\\left(X'X + \\lambda I\\right)$ is non-singular even if $X'X$ is not, which means that $\\hat\\beta^\\text{ridge}$ exists even if $\\hat\\beta$ is not defined. However, note also that the Ridge estimator requires careful choice of the hyperparameter $\\lambda$ which controls the *amount of regularization*: a larger value of $\\lambda$ implies *shrinkage* of the regression coefficient toward 0, a smaller value of $\\lambda$ reduces the bias of the resulting estimator.\n\n::: {.callout-note}\nNote that $X$ usually contains an intercept column with ones. As a general rule, the associated intercept coefficient is not penalized. In practice, this often implies that $y$ is simply demeaned before computing $\\hat\\beta^\\text{ridge}$.\n:::\n\nWhat about the statistical properties of the Ridge estimator? First, the bad news is that $\\hat\\beta^\\text{ridge}$ is a biased estimator of $\\beta$. However, the good news is that (under homoscedastic error terms) the variance of the Ridge estimator is guaranteed to be *smaller* than the variance of the OLS estimator. We encourage you to verify these two statements in the Exercises. As a result, we face a trade-off: The Ridge regression sacrifices some unbiasedness to achieve a smaller variance than the OLS estimator.\n\n### Lasso\n\n\\index{Regression!Lasso}\n\nAn alternative to Ridge regression is the Lasso (*l*east *a*bsolute *s*hrinkage and *s*election *o*perator). Similar to Ridge regression, the Lasso [@Tibshirani1996] is a penalized and biased estimator.\nThe main difference to Ridge regression is that Lasso does not only *shrink* coefficients but effectively selects variables by setting coefficients for *irrelevant* variables to zero. Lasso implements a $L_1$ penalization on the parameters such that: $$\\hat\\beta^\\text{Lasso} = \\arg\\min_\\beta \\left(Y - X\\beta\\right)'\\left(Y - X\\beta\\right)\\text{ s.t. } \\sum\\limits_{k=1}^K|\\beta_k| < c(\\lambda).$$ There is no closed-form solution for $\\hat\\beta^\\text{Lasso}$ in the above maximization problem, but efficient algorithms exist (e.g., the `glmnet` package for R and Python). Like for Ridge regression, the hyperparameter $\\lambda$ has to be specified beforehand.\n\n### Elastic Net\n\nThe Elastic Net [@Zou2005] combines $L_1$ with $L_2$ penalization and encourages a grouping effect, where strongly correlated predictors tend to be in or out of the model together. This more general framework considers the following optimization problem: $$\\hat\\beta^\\text{EN} = \\arg\\min_\\beta \\left(Y - X\\beta\\right)'\\left(Y - X\\beta\\right) + \\lambda(1-\\rho)\\sum\\limits_{k=1}^K|\\beta_k| +\\frac{1}{2}\\lambda\\rho\\sum\\limits_{k=1}^K\\beta_k^2$$ Now, we have to choose two hyperparameters: the *shrinkage* factor $\\lambda$ and the *weighting parameter* $\\rho$. The Elastic Net resembles Lasso for $\\rho = 0$ and Ridge regression for $\\rho = 1$. While efficient algorithms exist to compute the coefficients of penalized regressions, it is a good exercise to implement Ridge and Lasso estimation on your own before you use a dedicated back-end.\n\n## Data Preparation\n\nTo get started, we load the required packages and data.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nThe main focus is on the workflow behind the `tidymodels` package collection [@tidymodels], a collection of packages for modeling and ML using `tidyverse` principles. `tidymodels` comes with a handy workflow for all sorts of typical prediction tasks.\n@Kuhn2022 provide a thorough introduction into all `tidymodels` components. `glmnet` [@glmnet] was developed and released in sync with @Tibshirani1996 and provides an R implementation of Elastic Net estimation. The package `timetk` [@timetk] provides useful tools for time series data wrangling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nanoparquet)\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(scales)\nlibrary(furrr)\nlibrary(glmnet)\nlibrary(timetk)\n```\n:::\n\n\n### Python\n\nThe main focus is on the workflow behind the `scikit-learn` [@scikit-learn] package collection, a collection of packages for modeling and ML. `scikit-learn` comes with a handy workflow for all sorts of typical prediction tasks.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport polars as pl\nimport pandas as pd\nimport numpy as np\n\nfrom plotnine import *\nfrom mizani.formatters import percent_format, date_format\nfrom itertools import product\nfrom sklearn.model_selection import (\n  train_test_split, GridSearchCV, cross_val_score\n)\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.linear_model import ElasticNet, Lasso, Ridge\n```\n:::\n\n\n:::\n\n\n::: {.cell}\n\n:::\n\n\nIn this analysis, we use four different data sources that we load from our Parquet files introduced in [Accessing and Managing Financial Data](accessing-and-managing-financial-data.qmd) and [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd). We start with two different sets of factor portfolio returns which have been suggested as representing practical risk factor exposure and thus should be relevant when it comes to asset pricing applications.\n\n- The standard workhorse: monthly Fama-French 3 factor returns (market, small-minus-big, and high-minus-low book-to-market valuation sorts) defined in @Fama1992 and @Fama1993\n- Monthly q-factor returns from @Hou2015. The factors contain the size factor, the investment factor, the return-on-equity factor, and the expected growth factor\n\nNext, we include macroeconomic predictors which may predict the general stock market economy. Macroeconomic variables effectively serve as conditioning information such that their inclusion hints at the relevance of conditional models instead of unconditional asset pricing. We refer the interested reader to @Cochrane2009 on the role of conditioning information.\n\n- Our set of macroeconomic predictors comes from @Goyal2008. The data has been updated by the authors until 2021 and contains monthly variables that have been suggested as good predictors for the equity premium. Some of the variables are the dividend price ratio, earnings price ratio, stock variance, net equity expansion, treasury bill rate, and inflation\n\nFinally, we need a set of *test assets*. The aim is to understand which of the plenty factors and macroeconomic variable combinations prove helpful in explaining our test assets' cross-section of returns.\nIn line with many existing papers, we use monthly portfolio returns from 10 different industries according to the definition from [Kenneth French's homepage](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/Data_Library/det_10_ind_port.html) as test assets.\\index{Data!Fama-French factors}\\index{Data!q-factors}\\index{Data!Macroeconomic predictors}\\index{Data!Industry portfolios}\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactors_ff3_monthly <- read_parquet(\"data/factors_ff3_monthly.parquet\") |>\n  rename_with(~ str_c(\"factor_ff_\", .), -date)\n\nfactors_q_monthly <- read_parquet(\"data/factors_q_monthly.parquet\") |>\n  rename_with(~ str_c(\"factor_q_\", .), -date)\n\nmacro_predictors <- read_parquet(\"data/macro_predictors.parquet\") |>\n  rename_with(~ str_c(\"macro_\", .), -date) |>\n  select(-macro_rp_div)\n\nindustries_ff_monthly <- read_parquet(\"data/industries_ff_monthly.parquet\") |>\n  pivot_longer(-date, names_to = \"industry\", values_to = \"ret\") |>\n  arrange(desc(industry)) |>\n  mutate(industry = as_factor(industry))\n```\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfactors_ff3_monthly = (\n    pl.read_parquet(\"data/factors_ff3_monthly.parquet\")\n    .rename(lambda c: c if c == \"date\" else f\"factor_ff_{c}\")\n)\n\nfactors_q_monthly = (\n    pl.read_parquet(\"data/factors_q_monthly.parquet\")\n    .rename(lambda c: c if c == \"date\" else f\"factor_q_{c}\")\n)\n\nmacro_predictors = (\n    pl.read_parquet(\"data/macro_predictors.parquet\")\n    .rename(lambda c: c if c == \"date\" else f\"macro_{c}\")\n    .drop(\"macro_rp_div\")\n)\n\nindustries_ff_monthly = (\n    pl.read_parquet(\"data/industries_ff_monthly.parquet\")\n    .unpivot(index=\"date\", variable_name=\"industry\", value_name=\"ret\")\n)\n```\n:::\n\n\n:::\n\nWe combine all the monthly observations into one data frame.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- industries_ff_monthly |>\n  left_join(factors_ff3_monthly, join_by(date)) |>\n  left_join(factors_q_monthly, join_by(date)) |>\n  left_join(macro_predictors, join_by(date)) |>\n  mutate(\n    ret = ret - factor_ff_risk_free\n  ) |>\n  select(date, industry, ret_excess = ret, everything()) |>\n  drop_na()\n```\n:::\n\n\nOur data contains 24 columns of regressors with the 13 macro-variables and 10 factor returns for each month.\n@fig-1401 provides summary statistics for the 10 monthly industry excess returns in percent.\\index{Graph!Box plot}\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndata = (industries_ff_monthly\n  .join(factors_ff3_monthly, how=\"left\", on=\"date\")\n  .join(factors_q_monthly, how=\"left\", on=\"date\")\n  .join(macro_predictors, how=\"left\", on=\"date\")\n  .with_columns(ret_excess=pl.col(\"ret\") - pl.col(\"factor_ff_risk_free\"))\n  .drop(\"ret\")\n  .drop_nulls()\n)\n```\n:::\n\n\nOur data contains 24 columns of regressors with the 13 macro-variables and 10 factor returns for each month.\n@fig-1401 provides summary statistics for the 10 monthly industry excess returns in percent. One can see that the dispersion in the excess returns varies widely across industries. \\index{Graph!Box plot}\n\n:::\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  group_by(industry) |>\n  ggplot(aes(x = industry, y = ret_excess)) +\n  geom_boxplot() +\n  coord_flip() +\n  labs(\n    x = NULL,\n    y = NULL,\n    title = \"Excess return distributions by industry in percent\"\n  ) +\n  scale_y_continuous(\n    labels = percent\n  )\n```\n\n::: {.cell-output-display}\n![The box plots show the monthly dispersion of returns for 10 different industries.](factor-selection-via-machine-learning_files/figure-html/fig-1401-1.png){#fig-1401 fig-alt='Title: Excess return distributions by industry in percent. The figure shows boxplots that visualize the industry\\'s excess return distribution. All industry returns are centered around zero and exhibit substantial outliers in the magnitude of 20 percent on a monthly basis.' width=2100}\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndata_figure = (\n  ggplot(\n    data,\n    aes(x=\"industry\", y=\"ret_excess\")\n  )\n  + geom_boxplot()\n  + coord_flip()\n  + labs(x=\"\", y=\"\", title=\"Excess return distributions by industry in percent\")\n  + scale_y_continuous(labels=percent_format())\n)\ndata_figure.show()\n```\n\n::: {.cell-output-display}\n![The box plots show the monthly dispersion of returns for 10 different industries.](factor-selection-via-machine-learning_files/figure-html/factor-selection-via-machine-learning-fig-1401-py-1.png){fig-pos='htb' fig-alt='Title: Excess return distributions by industry in percent. The figure shows boxplots that visualize the industry\\'s excess return distribution. All industry returns are centered around zero and exhibit substantial outliers in the magnitude of 20 percent on a monthly basis.'}\n:::\n:::\n\n\n:::\n\n## The Machine Learning Workflow\n\nTo illustrate penalized linear regressions, we employ a collection of packages for modeling and ML. Using the ideas of Ridge and Lasso regressions, the following example guides you through (i) pre-processing the data (data split and variable mutation), (ii) building models, (iii) fitting models, and (iv) tuning models to create the \"best\" possible predictions.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nWe employ the `tidymodels` collection of packages for modeling and ML using `tidyverse` principles. You can simply use `install.packages(\"tidymodels\")` to get access to all the related packages. We recommend checking out the work of @Kuhn2022: They continuously write on their great book ['Tidy Modeling with R'](https://www.tmwr.org/) using tidy principles.\n\nThe `tidymodels` workflow encompasses the main stages of the modeling process: pre-processing of data, model fitting, and post-processing of results. As we demonstrate below, `tidymodels` provides efficient workflows that you can update with low effort.\n\nTo start, we restrict our analysis to just one industry: Manufacturing. We first split the sample into a *training* and a *test* set.\nFor that purpose, `tidymodels` provides the function `initial_time_split()` from the `rsample` package [@rsample].\nThe split takes the last 20% of the data as a test set, which is not used for any model tuning.\nWe use this test set to evaluate the predictive accuracy in an out-of-sample scenario.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsplit <- initial_time_split(\n  data |>\n    filter(industry == \"manuf\") |>\n    select(-industry),\n  prop = 4 / 5\n)\nsplit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<Training/Testing/Total>\n<546/137/683>\n```\n\n\n:::\n:::\n\n\nThe object `split` simply keeps track of the observations of the training and the test set.\nWe can call the training set with `training(split)`, while we can extract the test set with `testing(split)`.\n\n### Python\n\nWe employ the `scikit-learn` collection of packages for modeling and ML.\n\nTo start, we restrict our analysis to just one industry: Manufacturing. We split the sample into a *training* and a *test* set, holding out the last 20% of the data as a test set, which is not used for any model tuning. We use this test set to evaluate the predictive accuracy in an out-of-sample scenario.\n\n:::\n\n### Pre-process data\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nRecipes help you pre-process your data before training your model. Recipes are a series of pre-processing steps such as variable selection, transformation, or conversion of qualitative predictors to indicator variables. Each recipe starts with a `formula` that defines the general structure of the dataset and the role of each variable (regressor or dependent variable). For our dataset, our recipe contains the following steps before we fit any model:\n\n-   Our formula defines that we want to explain excess returns with all available predictors. The regression equation thus takes the form\n$$r_{t} = \\alpha_0 + \\left(\\tilde f_t \\otimes \\tilde z_t\\right)B + \\varepsilon_t $$ where $r_t$ is the vector of industry excess returns at time $t$ and $\\tilde f_t$ and $\\tilde z_t$ are the (standardized) vectors of factor portfolio returns and macroeconomic variables\n- We exclude the column *month* from the analysis\n- We include all interaction terms between factors and macroeconomic predictors\n- We demean and scale each regressor such that the standard deviation is one\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec <- recipe(ret_excess ~ ., data = training(split)) |>\n  step_rm(date) |>\n  step_interact(terms = ~ contains(\"factor\"):contains(\"macro\")) |>\n  step_normalize(all_predictors())\n```\n:::\n\n\nA table of all available recipe steps can be found [in the `tidymodels` documentation.](https://www.tidymodels.org/find/recipes/) As of 2026, more than 150 different processing steps are available! One important point: The definition of a recipe does not trigger any calculations yet but rather provides a *description* of the tasks to be applied. As a result, it is very easy to *reuse* recipes for different models and thus make sure that the outcomes are comparable as they are based on the same input.\nIn the example above, it does not make a difference whether you use the input `data = training(split)` or `data = testing(split)`.\nAll that matters at this early stage are the column names and types.\n\nWe can apply the recipe to any data with a suitable structure. The code below combines two different functions: `prep()` estimates the required parameters from a training set that can be applied to other datasets later. `bake()` applies the processed computations to new data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_prep <- prep(rec, training(split))\n```\n:::\n\nThe object `data_prep` contains information related to the different preprocessing steps applied to the training data: E.g., it is necessary to compute sample means and standard deviations to center and scale the variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_bake <- bake(data_prep,\n  new_data = testing(split)\n)\ndata_bake\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 137 × 154\n  factor_ff_mkt_excess factor_ff_smb factor_ff_hml\n                 <dbl>         <dbl>         <dbl>\n1               0.0709       -0.940         -0.150\n2               0.448         0.0896         0.296\n3               0.489         0.0738         0.430\n4              -0.478        -0.412          1.09 \n5               0.0688        0.121         -0.426\n# ℹ 132 more rows\n# ℹ 151 more variables: factor_ff_risk_free <dbl>,\n#   factor_q_risk_free <dbl>, factor_q_mkt_excess <dbl>,\n#   factor_q_me <dbl>, factor_q_ia <dbl>, factor_q_roe <dbl>,\n#   factor_q_eg <dbl>, macro_dp <dbl>, macro_dy <dbl>,\n#   macro_ep <dbl>, macro_de <dbl>, macro_svar <dbl>,\n#   macro_bm <dbl>, macro_ntis <dbl>, macro_tbl <dbl>, …\n```\n\n\n:::\n:::\n\n\nNote that the resulting data contains the 137 observations from the test set and 154 columns. Why so many? Recall that the recipe states to compute every possible interaction term between the factors and predictors, which increases the dimension of the data matrix substantially.\n\nYou may ask at this stage: why should I use a recipe instead of simply using the data wrangling commands such as `mutate()` or `select()`? `tidymodels` beauty is that a lot is happening under the hood. Recall, that for the simple scaling step, you actually have to compute the standard deviation of each column, then *store* this value, and apply the identical transformation to a different dataset, e.g., `testing(split)`. A prepped `recipe` stores these values and hands them on once you `bake()` a novel dataset. Easy as pie with `tidymodels`, isn't it?\n\n### Python\n\nWe want to explain excess returns with all available predictors. The regression equation thus takes the form\n$$\nr_{t} = \\alpha_0 + \\left(\\tilde f_t \\otimes \\tilde z_t\\right)B + \\varepsilon_t\n$$\n\nwhere $r_t$ is the vector of industry excess returns at time $t$, $\\otimes$ denotes the Kronecker product and $\\tilde f_t$ and $\\tilde z_t$ are the (standardized) vectors of factor portfolio returns and macroeconomic variables.\n\nWe hence perform the following pre-processing steps:\n\n- We exclude the column *month* from the analysis\n- We include all interaction terms between factors and macroeconomic predictors\n- We demean and scale each regressor such that the standard deviation is one\n\nScaling is often necessary in machine learning applications, especially when combining variables of different magnitudes or units, or when using algorithms sensitive to feature scales (e.g., gradient descent-based algorithms). We use `ColumnTransformer()` to scale all regressors using `StandardScaler()`. The `remainder=\"drop\"` ensures that only the specified columns are retained in the output, and others are dropped. The option `verbose_feature_names_out=False` ensures that the output feature names remain unchanged. We construct each interaction term as a `polars` expression that multiplies a macroeconomic predictor with a factor return and assigns it a descriptive name via `alias()`, and then add all of these columns to the data with `with_columns()`. Because `scikit-learn` operates on `pandas` objects, we convert the data frame with `to_pandas()` at the boundary before feeding it into the modeling pipeline.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmacro_variables = [c for c in data.columns if c.startswith(\"macro\")]\nfactor_variables = [c for c in data.columns if c.startswith(\"factor\")]\n\ncolumn_combinations = list(product(macro_variables, factor_variables))\n\ninteraction_terms = [\n    (pl.col(macro_column) * pl.col(factor_column)).alias(\" x \".join((macro_column, factor_column)))\n    for macro_column, factor_column in column_combinations\n]\n\ndata = data.with_columns(interaction_terms)\n\npreprocessor = ColumnTransformer(\n  transformers=[\n    (\"scale\", StandardScaler(),\n    [col for col in data.columns\n      if col not in [\"ret_excess\", \"date\", \"industry\"]])\n  ],\n  remainder=\"drop\",\n  verbose_feature_names_out=False\n)\n```\n:::\n\n\n:::\n\n### Build a model\n\n\\index{Regression}\nNext, we can build an actual model based on our pre-processed data. In line with the definition above, we estimate regression coefficients of a Lasso regression such that we get\n$$\\begin{aligned}\\hat\\beta_\\lambda^\\text{Lasso} = \\arg\\min_\\beta \\left(Y - X\\beta\\right)'\\left(Y - X\\beta\\right) + \\lambda\\sum\\limits_{k=1}^K|\\beta_k|.\\end{aligned}$$ We want to emphasize that the workflow for *any* model is very similar, irrespective of the specific model. As you will see further below, it is straightforward to fit Ridge regression coefficients and, later, Neural networks or Random forests with basically the same code.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nThe structure is always as follows: create a so-called `workflow()` and use the `fit()` function. A table with all available model APIs is available [here.](https://www.tidymodels.org/find/parsnip/)\nFor now, we start with the linear regression model with a given value for the penalty factor $\\lambda$. In the setup below, `mixture` denotes the value of $\\rho$, hence setting `mixture = 1` implies the Lasso.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model <- linear_reg(\n  penalty = 0.0001,\n  mixture = 1\n) |>\n  set_engine(\"glmnet\", intercept = FALSE)\n```\n:::\n\n\nThat's it - we are done! The object `lm_model` contains the definition of our model with all required information. Note that `set_engine(\"glmnet\")` indicates the API character of the `tidymodels` workflow: Under the hood, the package `glmnet` is doing the heavy lifting, while `linear_reg()` provides a unified framework to collect the inputs. The `workflow` ends with combining everything necessary for the serious data science workflow, namely, a recipe and a model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_fit <- workflow() |>\n  add_recipe(rec) |>\n  add_model(lm_model)\nlm_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n══ Workflow ═════════════════════════════════════════════════════════\nPreprocessor: Recipe\nModel: linear_reg()\n\n── Preprocessor ─────────────────────────────────────────────────────\n3 Recipe Steps\n\n• step_rm()\n• step_interact()\n• step_normalize()\n\n── Model ────────────────────────────────────────────────────────────\nLinear Regression Model Specification (regression)\n\nMain Arguments:\n  penalty = 1e-04\n  mixture = 1\n\nEngine-Specific Arguments:\n  intercept = FALSE\n\nComputational engine: glmnet \n```\n\n\n:::\n:::\n\n\n### Python\n\nIn the application at hand, $X$ contains 130 columns with all possible interactions between factor returns and macroeconomic variables. We start with the linear regression model with an arbitrarily chosen value for the penalty factor $\\lambda$ (denoted as `alpha=0.007` in the code below). In the setup below, `l1_ratio` denotes the value of $1-\\rho$, hence setting `l1_ratio=1` implies the Lasso.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlm_model = ElasticNet(\n  alpha=0.007,\n  l1_ratio=1,\n  max_iter=5000,\n  fit_intercept=False\n)\n\nlm_pipeline = Pipeline([\n  (\"preprocessor\", preprocessor),\n  (\"regressor\", lm_model)\n])\n```\n:::\n\n\nThat's it - we are done! The object `lm_pipeline` contains the definition of our model with all required information, in particular the pre-processing steps and the regression model.\n\n:::\n\n### Fit a model\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nWith the `workflow` from above, we are ready to use `fit()`. Typically, we use training data to fit the model.\nThe training data is pre-processed according to our recipe steps, and the Lasso regression coefficients are computed.\nFirst, we focus on the predicted values $\\hat{y}_t = x_t\\hat\\beta^\\text{Lasso}.$ @fig-1402 illustrates the projections for the *entire* time series of the manufacturing industry portfolio returns. The grey area indicates the out-of-sample period, which we did not use to fit the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_values <- lm_fit |>\n  fit(data = training(split)) |>\n  augment(data |> filter(industry == \"manuf\")) |>\n  select(date,\n         \"Fitted value\" = .pred,\n         \"Realization\" = ret_excess\n  ) |>\n  pivot_longer(-date, names_to = \"Variable\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_values |>\n  ggplot(aes(\n    x = date,\n    y = value,\n    color = Variable,\n    linetype = Variable\n    )) +\n  geom_line() +\n  labs(\n    x = NULL,\n    y = NULL,\n    color = NULL,\n    linetype = NULL,\n    title = \"Monthly realized and fitted manufacturing industry risk premia\"\n  ) +\n  scale_x_date(\n    breaks = function(x) {\n      seq.Date(\n        from = min(x),\n        to = max(x),\n        by = \"5 years\"\n      )\n    },\n    minor_breaks = function(x) {\n      seq.Date(\n        from = min(x),\n        to = max(x),\n        by = \"1 years\"\n      )\n    },\n    expand = c(0, 0),\n    labels = date_format(\"%Y\")\n  ) +\n  scale_y_continuous(\n    labels = percent\n  ) +\n  annotate(\"rect\",\n    xmin = testing(split) |> pull(date) |> min(),\n    xmax = testing(split) |> pull(date) |> max(),\n    ymin = -Inf, ymax = Inf,\n    alpha = 0.5, fill = \"grey70\"\n  )\n```\n\n::: {.cell-output-display}\n![The figure shows monthly realized and fitted manufacturing industry risk premium. The grey area corresponds to the out of sample period.](factor-selection-via-machine-learning_files/figure-html/fig-1402-1.png){#fig-1402 fig-alt='Title: Monthly realized and fitted manufacturing industry risk premium. The figure shows the time series of realized and predicted manufacturing industry risk premiums. The figure seems to indicate that the predictions capture most of the return dynamics.' width=2100}\n:::\n:::\n\n\n### Python\n\nWith the pipeline from above, we are ready to fit it to the data. Typically, we use training data to fit the model. The training data is pre-processed according to our pipeline steps, and the Lasso regression coefficients are computed. For illustrative purposes, we focus on the manufacturing industry for now.\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndata_manufacturing = data.filter(pl.col(\"industry\") == \"manuf\").sort(\"date\")\n\n# Hold out the last 20% as a test set (matches R's initial_time_split(prop = 4/5)).\nn_train = int(len(data_manufacturing) * 4 / 5)\ndata_manufacturing_training = data_manufacturing.head(n_train)\n\n# scikit-learn operates on pandas/numpy, so we convert at the modeling boundary.\nlm_fit = lm_pipeline.fit(\n  data_manufacturing_training.to_pandas(),\n  data_manufacturing_training[\"ret_excess\"].to_numpy()\n)\n```\n:::\n\n\nFirst, we focus on the in-sample predicted values $\\hat{y}_t = x_t\\hat\\beta^\\text{Lasso}.$ @fig-1402 illustrates the projections for the *entire* time series of the manufacturing industry portfolio returns. The grey area indicates the out-of-sample period, which we did not use to fit the model.\n\n\n::: {.cell}\n\n```{.python .cell-code}\npredicted_values = (\n  pl.DataFrame({\n    \"date\": data_manufacturing[\"date\"],\n    \"Fitted value\": lm_fit.predict(data_manufacturing.to_pandas()),\n    \"Realization\": data_manufacturing[\"ret_excess\"]\n  })\n  .unpivot(index=\"date\", variable_name=\"Variable\", value_name=\"return\")\n)\n\npredicted_values_figure = (\n  ggplot(\n    predicted_values,\n    aes(x=\"date\", y=\"return\", color=\"Variable\", linetype=\"Variable\")\n  )\n  + annotate(\n    \"rect\",\n    xmin=data_manufacturing_training[\"date\"].max(),\n    xmax=data_manufacturing[\"date\"].max(),\n    ymin=-np.inf, ymax=np.inf,\n    alpha=0.25, fill=\"#808080\"\n  )\n  + geom_line()\n  + labs(\n      x=\"\", y=\"\", color=\"\", linetype=\"\",\n      title=\"Monthly realized and fitted manufacturing industry risk premia\"\n    )\n  + scale_x_date(date_breaks=\"5 years\", date_labels=\"%Y\")\n  + scale_y_continuous(labels=percent_format())\n)\npredicted_values_figure.show()\n```\n\n::: {.cell-output-display}\n![The figure shows monthly realized and fitted manufacturing industry risk premium. The grey area corresponds to the out of sample period.](factor-selection-via-machine-learning_files/figure-html/factor-selection-via-machine-learning-fig-1402-py-1.png){fig-pos='htb' fig-alt='Title: Monthly realized and fitted manufacturing industry risk premium. The figure shows the time series of realized and predicted manufacturing industry risk premiums. The figure seems to indicate that the predictions capture most of the return dynamics.'}\n:::\n:::\n\n\n:::\n\nWhat do the estimated coefficients look like? To analyze these values, it is worth computing the coefficients $\\hat\\beta^\\text{Lasso}$ directly. The code below estimates the coefficients for the Lasso and Ridge regression for the processed training data sample.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nTo illustrate the difference between the `tidymodels` workflow and the underlying `glmnet` package, we compute the coefficients $\\hat\\beta^\\text{Lasso}$ directly. Note that `glmnet` actually takes a vector `y` and the matrix of regressors $X$ as input. Moreover, `glmnet` requires choosing the penalty parameter $\\alpha$, which corresponds to $\\rho$ in the notation above. When using the `tidymodels` model API, such details do not need consideration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- data_bake |>\n  select(-ret_excess) |>\n  as.matrix()\ny <- data_bake |> pull(ret_excess)\n\nfit_lasso <- glmnet(\n  x = x,\n  y = y,\n  alpha = 1,\n  intercept = FALSE,\n  standardize = FALSE,\n  lambda.min.ratio = 0\n)\n\nfit_ridge <- glmnet(\n  x = x,\n  y = y,\n  alpha = 0,\n  intercept = FALSE,\n  standardize = FALSE,\n  lambda.min.ratio = 0\n)\n```\n:::\n\n\nThe objects `fit_lasso` and `fit_ridge` contain an entire sequence of estimated coefficients for multiple values of the penalty factor $\\lambda$. @fig-1403 illustrates the trajectories of the regression coefficients as a function of the penalty factor. Both Lasso and Ridge coefficients converge to zero as the penalty factor increases.\\index{Graph!ML prediction path}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  tidy(fit_lasso) |> mutate(Model = \"Lasso\"),\n  tidy(fit_ridge) |> mutate(Model = \"Ridge\")\n) |>\n  rename(\"Variable\" = term) |>\n  ggplot(aes(x = lambda, y = estimate, color = Variable)) +\n  geom_line() +\n  scale_x_log10() +\n  facet_wrap(~ Model, scales = \"free_x\") +\n  labs(\n    x = \"Penalty factor (lambda)\", y = NULL,\n    title = \"Estimated coefficient paths for different penalty factors\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![The figure shows estimated coefficient paths for different penalty factors. The penalty parameters are chosen iteratively to resemble the path from no penalization to a model that excludes all variables.](factor-selection-via-machine-learning_files/figure-html/fig-1403-1.png){#fig-1403 fig-alt='Title: Estimated coefficient paths for different penalty factors. The figure shows how estimated lasso and ridge coefficients tend to zero for a higher penalty parameter. Ridge trace is smooth, and Lasso exhibits non-linear behavior.' width=2100}\n:::\n:::\n\n\n::: {.callout-note}\nOne word of caution: The package `glmnet` computes estimates of the coefficients $\\hat\\beta$ based on numerical optimization procedures.\nAs a result, the estimated coefficients for the [special case](https://parsnip.tidymodels.org/reference/glmnet-details.html) with no regularization ($\\lambda = 0$) can deviate from the standard OLS estimates.\n:::\n\n### Python\n\nWe estimate the coefficients $\\hat\\beta^\\text{Lasso}$ directly for a grid of different $\\lambda$'s, using the `Lasso` and `Ridge` estimators from `scikit-learn` on the pre-processed regressor matrix.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = preprocessor.fit_transform(data_manufacturing.to_pandas())\ny = data_manufacturing[\"ret_excess\"].to_numpy()\n\nalphas = np.logspace(-5, 5, 100)\n\ncoefficients_lasso = []\nfor a in alphas:\n    lasso = Lasso(alpha=a, fit_intercept=False)\n    coefficients_lasso.append(lasso.fit(x, y).coef_)\n\ncoefficients_lasso = (\n  pl.DataFrame(np.vstack(coefficients_lasso), orient=\"row\")\n  .with_columns(alpha=pl.Series(alphas), model=pl.lit(\"Lasso\"))\n  .unpivot(index=[\"alpha\", \"model\"])\n)\n\ncoefficients_ridge = []\nfor a in alphas:\n    ridge = Ridge(alpha=a, fit_intercept=False)\n    coefficients_ridge.append(ridge.fit(x, y).coef_)\n\ncoefficients_ridge = (\n  pl.DataFrame(np.vstack(coefficients_ridge), orient=\"row\")\n  .with_columns(alpha=pl.Series(alphas), model=pl.lit(\"Ridge\"))\n  .unpivot(index=[\"alpha\", \"model\"])\n)\n```\n:::\n\n\nThe dataframes `coefficients_lasso` and `coefficients_ridge` contain an entire sequence of estimated coefficients for multiple values of the penalty factor $\\lambda$. @fig-1403 illustrates the trajectories of the regression coefficients as a function of the penalty factor. Both Lasso and Ridge coefficients converge to zero as the penalty factor increases.\\index{Graph!Coefficient path}\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncoefficients_figure = (\n  ggplot(\n    pl.concat([coefficients_lasso, coefficients_ridge]),\n    aes(x=\"alpha\", y=\"value\", color=\"variable\")\n  )\n  + geom_line()\n  + facet_wrap(\"model\")\n  + labs(\n      x=\"Penalty factor (lambda)\", y=\"\",\n      title=\"Estimated coefficient paths for different penalty factors\"\n    )\n  + scale_x_log10()\n  + theme(legend_position=\"none\"))\ncoefficients_figure.show()\n```\n\n::: {.cell-output-display}\n![The figure shows estimated coefficient paths for different penalty factors. The penalty parameters are chosen iteratively to resemble the path from no penalization to a model that excludes all variables.](factor-selection-via-machine-learning_files/figure-html/factor-selection-via-machine-learning-fig-1403-py-1.png){fig-pos='htb' fig-alt='Title: Estimated coefficient paths for different penalty factors. The figure shows how estimated lasso and ridge coefficients tend to zero for a higher penalty parameter. Ridge trace is smooth, and Lasso exhibits non-linear behavior.'}\n:::\n:::\n\n\n:::\n\n### Tune a model\n\nTo compute $\\hat\\beta_\\lambda^\\text{Lasso}$, we simply imposed a value for the penalty hyperparameter $\\lambda$. Model tuning is the process of optimally selecting such hyperparameters through *cross-validation*. Again, we refer to any treatment of cross-validation to get a more detailed discussion of the statistical underpinnings. Here we focus on the general idea and the implementation.\n\nThe goal for choosing $\\lambda$ (or any other hyperparameter, e.g., $\\rho$ for the Elastic Net) is to find a way to produce predictors $\\hat{Y}$ for an outcome $Y$ that minimizes the mean squared prediction error $\\text{MSPE} = E\\left( \\frac{1}{T}\\sum_{t=1}^T (\\hat{y}_t - y_t)^2 \\right)$. Unfortunately, the MSPE is not directly observable. We can only compute an estimate because our data is random and because we do not observe the entire population.\\index{MSPE}\n\nObviously, if we train an algorithm on the same data that we use to compute the error, our estimate $\\text{MSPE}$ would indicate way better predictive accuracy than what we can expect in real out-of-sample data. The result is called overfitting.\n\nCross-validation is a technique that allows us to alleviate this problem. We approximate the true MSPE as the average of many MSPE obtained by creating predictions for $K$ new random samples of the data, none of them used to train the algorithm $\\frac{1}{K} \\sum_{k=1}^K \\frac{1}{T}\\sum_{t=1}^T \\left(\\hat{y}_t^k - y_t^k\\right)^2$. In practice, this is done by carving out a piece of our data and pretending it is an independent sample. We again divide the data into a training set and a test set. The MSPE on the test set is our measure for actual predictive ability, while we use the training set to fit models with the aim to find the *optimal* hyperparameter values. To do so, we further divide our training sample into (several) subsets, fit our model for a grid of potential hyperparameter values (e.g., $\\lambda$), and evaluate the predictive accuracy on an *independent* sample. This works as follows:\n\n1.  Specify a grid of hyperparameters\n2.  Obtain predictors $\\hat{y}_i(\\lambda)$ to denote the predictors for the used parameters $\\lambda$\n3.  Compute $$\n    \\text{MSPE}(\\lambda) = \\frac{1}{K} \\sum_{k=1}^K \\frac{1}{T}\\sum_{t=1}^T \\left(\\hat{y}_t^k(\\lambda) - y_t^k\\right)^2\n    $$ With K-fold cross-validation, we do this computation $K$ times. Simply pick a validation set with $M=T/K$ observations at random and think of these as random samples $y_1^k, \\dots, y_{\\tilde{T}}^k$, with $k=1$\n\nHow should you pick $K$? Large values of $K$ are preferable because the training data better imitates the original data. However, larger values of $K$ will have much higher computation time.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n`tidymodels` provides all required tools to conduct $K$-fold cross-validation. We just have to update our model specification and let `tidymodels` know which parameters to tune. In our case, we specify the penalty factor $\\lambda$ as well as the mixing factor $\\rho$ as *free* parameters. Note that it is simple to change an existing `workflow` with `update_model()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model <- linear_reg(\n  penalty = tune(),\n  mixture = tune()\n) |>\n  set_engine(\"glmnet\")\n\nlm_fit <- lm_fit |>\n  update_model(lm_model)\n```\n:::\n\n\nFor our sample, we consider a time-series cross-validation sample. This means that we tune our models with rolling-origin cross-validation, where each fold trains on a five-year window and validates on the subsequent, non-overlapping four-year window. For a grid of possible hyperparameters, we then fit the model for each fold and evaluate $\\hat{\\text{MSPE}}$ in the corresponding validation set. Finally, we select the model specification with the lowest MSPE in the validation set. First, we define the cross-validation folds based on our training data only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shared rolling-origin folds: a five-year (60-month) training window and a\n# subsequent, non-overlapping four-year (48-month) validation window. We build\n# the folds from explicit row indices so they are identical to the Python ones.\nmake_rolling_folds <- function(df, train_len = 60, assess_len = 48, step = 48) {\n  df <- arrange(df, date)\n  n <- nrow(df)\n  starts <- seq.int(0L, n - (train_len + assess_len), by = step)\n  splits <- lapply(starts, function(s) {\n    make_splits(\n      list(analysis   = seq.int(s + 1L, s + train_len),\n           assessment = seq.int(s + train_len + 1L, s + train_len + assess_len)),\n      data = df\n    )\n  })\n  manual_rset(splits, ids = paste0(\"Slice\", seq_along(splits)))\n}\n\ndata_folds <- make_rolling_folds(training(split))\ndata_folds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Manual resampling \n# A tibble: 10 × 2\n  splits          id    \n  <list>          <chr> \n1 <split [60/48]> Slice1\n2 <split [60/48]> Slice2\n3 <split [60/48]> Slice3\n4 <split [60/48]> Slice4\n5 <split [60/48]> Slice5\n# ℹ 5 more rows\n```\n\n\n:::\n:::\n\n\nThen, we evaluate the performance for a grid of different penalty values. `tidymodels` provides functionalities to construct a suitable grid of hyperparameters with `grid_regular`. The code chunk below creates a $20 \\times 3$ hyperparameters grid. Then, the function `tune_grid()` evaluates all the models for each fold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_tune <- lm_fit |>\n  tune_grid(\n    resample = data_folds,\n    grid = grid_regular(penalty(), mixture(), levels = c(20, 3)),\n    metrics = metric_set(rmse)\n  )\n```\n:::\n\n\nAfter the tuning process, we collect the evaluation metrics (the root mean-squared error in our example) to identify the *optimal* model. @fig-1404 illustrates the average validation set's root mean-squared error for each value of $\\lambda$ and $\\rho$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(lm_tune) +\n  aes(linetype = `Proportion of Lasso Penalty`) +\n  guides(linetype = \"none\") +\n  labs(\n    x = \"Penalty factor (lambda)\",\n    y = \"Root MSPE\",\n    title = \"Root MSPE for different penalty factors\"\n  ) +\n  scale_x_log10()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for x is already present.\nAdding another scale for x, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![The figure shows root MSPE for different penalty factors. Evaluation of manufacturing excess returns for different penalty factors (lambda) and proportions of Lasso penalty (rho). 1.0 indicates Lasso, 0.5 indicates Elastic Net, and 0.0 indicates Ridge.](factor-selection-via-machine-learning_files/figure-html/fig-1404-1.png){#fig-1404 fig-alt='Title: Root MSPE for different penalty factors. The figure shows that more regularization does not affect the selected models in a meaningful fashion. At some point, the Elastic Net prediction error drops, which indicates the selected model. MSPE increases again for high penalization values.' width=2100}\n:::\n:::\n\n\n@fig-1404 shows that the cross-validated MSPE drops for Lasso and Elastic Net and spikes afterward. For Ridge regression, the MSPE increases above a certain threshold. Recall that the larger the regularization, the more restricted the model becomes. Thus, we would choose the model with the lowest MSPE.\n\n### Python\n\n`scikit-learn` provides all required tools to conduct $K$-fold cross-validation. We just have to update our model specification. In our case, we specify the penalty factor $\\lambda$ as well as the mixing factor $\\rho$ as *free* parameters.\n\nFor our sample, we consider a time-series cross-validation sample. This means that we tune our models with rolling-origin cross-validation, where each fold trains on a five-year window and validates on the subsequent, non-overlapping four-year window. For a grid of possible hyperparameters, we then fit the model for each fold and evaluate $\\hat{\\text{MSPE}}$ in the corresponding validation set. Finally, we select the model specification with the lowest MSPE in the validation set.\n\n`scikit-learn` provides functionalities to construct a suitable grid of hyperparameters with `GridSearchCV()`. The code chunk below creates a $100 \\times 3$ hyperparameters grid. Then, the method `fit()` evaluates all the models for each fold.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nalphas = np.logspace(-6, 2, 100)\n\n# Shared rolling-origin folds: a five-year (60-month) training window and a\n# subsequent, non-overlapping four-year (48-month) validation window, built from\n# explicit row indices so they are identical to the R folds.\ndef make_rolling_folds(n, train_len=60, assess_len=48, step=48):\n  return [\n    (np.arange(s, s + train_len),\n     np.arange(s + train_len, s + train_len + assess_len))\n    for s in range(0, n - (train_len + assess_len) + 1, step)\n  ]\n\ndata_folds = make_rolling_folds(n_train)\n\nparams = {\n  \"regressor__alpha\": alphas,\n  \"regressor__l1_ratio\": (0.0, 0.5, 1)\n}\n\nfinder = GridSearchCV(\n  lm_pipeline,\n  param_grid=params,\n  scoring=\"neg_root_mean_squared_error\",\n  cv=data_folds\n)\n\nfinder = finder.fit(\n  data_manufacturing_training.to_pandas(),\n  data_manufacturing_training[\"ret_excess\"].to_numpy()\n)\n```\n:::\n\n\nAfter the tuning process, we collect the evaluation metrics (the root mean-squared error in our example) to identify the *optimal* model. @fig-1404 illustrates the average validation set's root mean-squared error for each value of $\\lambda$ and $\\rho$.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvalidation = (\n  pl.DataFrame({\n    \"param_regressor__alpha\": np.asarray(\n      finder.cv_results_[\"param_regressor__alpha\"], dtype=float\n    ),\n    \"param_regressor__l1_ratio\": np.asarray(\n      finder.cv_results_[\"param_regressor__l1_ratio\"], dtype=str\n    ),\n    \"mean_test_score\": finder.cv_results_[\"mean_test_score\"],\n    \"rank_test_score\": finder.cv_results_[\"rank_test_score\"]\n  })\n  .with_columns(mspe=-pl.col(\"mean_test_score\"))\n)\n\nbest_model = validation.sort(\"rank_test_score\").head(1)\nbest_alpha = best_model[\"param_regressor__alpha\"][0]\nbest_rho = float(best_model[\"param_regressor__l1_ratio\"][0])\n\nvalidation_figure = (\n  ggplot(\n    validation,\n    aes(x=\"param_regressor__alpha\", y=\"mspe\",\n        color=\"param_regressor__l1_ratio\",\n        shape=\"param_regressor__l1_ratio\",\n        group=\"param_regressor__l1_ratio\")\n  )\n  + geom_point()\n  + geom_line()\n  + labs(\n      x =\"Penalty factor (lambda)\", y=\"Root MSPE\",\n      title=\"Root MSPE for different penalty factors\",\n      color=\"Proportion of Lasso Penalty\",\n      shape=\"Proportion of Lasso Penalty\"\n    )\n  + scale_x_log10()\n  + guides(linetype=\"none\")\n)\nvalidation_figure.show()\n```\n\n::: {.cell-output-display}\n![The figure shows root MSPE for different penalty factors. Evaluation of manufacturing excess returns for different penalty factors (lambda) and proportions of Lasso penalty (rho). 1.0 indicates Lasso, 0.5 indicates Elastic Net, and 0.0 indicates Ridge.](factor-selection-via-machine-learning_files/figure-html/factor-selection-via-machine-learning-fig-1404-py-1.png){fig-pos='htb' fig-alt='Title: Root MSPE for different penalty factors. The figure shows that more regularization does not affect the selected models in a meaningful fashion. At some point, the Elastic Net prediction error drops, which indicates the selected model. MSPE increases again for high penalization values.'}\n:::\n:::\n\n\n@fig-1404 shows that the MSPE drops faster for Lasso and Elastic Net compared to Ridge regressions as penalty factor increases. However, for higher penalty factors, the MSPE for Ridge regressions dips below the others, which both slightly increase again above a certain threshold. Recall that the larger the regularization, the more restricted the model becomes. The best performing model yields a penalty parameter (`alpha`) of 0.005 and a mixture factor ($\\rho$) of 0.5.\n\n:::\n\n### Parallelized workflow\n\nOur starting point was the question: Which factors determine industry returns? While @Avramov2022b provide a Bayesian analysis related to the research question above, we choose a simplified approach: To illustrate the entire workflow, we now run the penalized regressions for all ten industries.\nWe want to identify relevant variables by fitting Lasso models for each industry returns time series. More specifically, we perform cross-validation for each industry to identify the optimal penalty factor $\\lambda$.\n\nFirst, we define the Lasso model with one tuning parameter.\n\n::: {.panel-tabset group=\"language\"}\n### R\n\nThen, we use the set of `finalize_*()`-functions that take a list or tibble of tuning parameter values and update objects with those values. After determining the best model, we compute the final fit on the entire training set and analyze the estimated coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlasso_model <- linear_reg(\n  penalty = tune(),\n  mixture = 1\n) |>\n  set_engine(\"glmnet\")\n\nlm_fit <- lm_fit |>\n  update_model(lasso_model)\n```\n:::\n\n\nThe following task can be easily parallelized to reduce computing time substantially. We use the parallelization capabilities of `furrr`. Note that we can also just recycle all the steps from above and collect them in a function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect_variables <- function(input) {\n  # Split into training and testing data\n  split <- initial_time_split(input, prop = 4 / 5)\n\n  # Data folds for cross-validation (same rolling-origin scheme as above)\n  data_folds <- make_rolling_folds(training(split))\n\n  # Model tuning with the Lasso model\n  lm_tune <- lm_fit |>\n    tune_grid(\n      resample = data_folds,\n      grid = grid_regular(penalty(), levels = c(10)),\n      metrics = metric_set(rmse)\n    )\n\n  # Identify the best model and fit with the training data\n  lasso_lowest_rmse <- lm_tune |> select_by_one_std_err(\"rmse\")\n  lasso_final <- finalize_workflow(lm_fit, lasso_lowest_rmse)\n  lasso_final_fit <- last_fit(lasso_final, split, metrics = metric_set(rmse))\n\n  # Extract the estimated coefficients\n  estimated_coefficients <- lasso_final_fit |>\n    extract_fit_parsnip() |>\n    tidy() |>\n    mutate(\n      term = str_remove_all(term, \"factor_|macro_|industry_\")\n    )\n\n  return(estimated_coefficients)\n}\n\n# Parallelization\nplan(sequential)\n\n# Computation by industry\nselected_factors <- data |>\n  nest(data = -industry) |>\n  mutate(selected_variables = future_map(\n    data, select_variables,\n    .options = furrr_options(seed = TRUE)\n  ))\n```\n:::\n\n\nWhat has just happened? In principle, exactly the same as before but instead of computing the Lasso coefficients for one industry, we did it for ten in parallel. The final option `seed = TRUE` is required to make the cross-validation process reproducible.\nNow, we just have to do some housekeeping and keep only variables that Lasso does *not* set to zero. We illustrate the results in a heat map in @fig-1405.\\index{Graph!Heat map}\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlm_model = Lasso(fit_intercept=False, max_iter=5000)\n\nparams = {\"regressor__alpha\": alphas}\n\nlm_pipeline = Pipeline([\n  (\"preprocessor\", preprocessor),\n  (\"regressor\", lm_model)\n])\n```\n:::\n\n\nThe following task can be easily parallelized to reduce computing time, but we use a simple loop for ease of exposition.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nall_industries = data[\"industry\"].unique(maintain_order=True)\n\nresults = []\nfor industry in all_industries:\n  print(industry)\n  industry_training = (\n    data.filter(pl.col(\"industry\") == industry).sort(\"date\").head(n_train)\n  )\n\n  finder = GridSearchCV(\n    lm_pipeline,\n    param_grid=params,\n    scoring=\"neg_mean_squared_error\",\n    cv=data_folds\n  )\n\n  finder = finder.fit(\n    industry_training.to_pandas(),\n    industry_training[\"ret_excess\"].to_numpy()\n  )\n  results.append(finder.best_estimator_.named_steps.regressor.coef_ != 0)\n```\n\n```{.python .cell-code}\n\nselected_factors = (\n  pl.DataFrame({\"variable\": lm_pipeline[:-1].get_feature_names_out()})\n  .with_columns(\n    variable=pl.col(\"variable\").str.replace_all(\"factor_|ff_|q_|macro_\", \"\")\n  )\n  .with_columns([pl.Series(industry, result)\n                 for industry, result in zip(all_industries, results)])\n  .unpivot(index=\"variable\", variable_name=\"industry\", value_name=\"value\")\n  .filter(pl.col(\"value\"))\n)\n```\n:::\n\n\nWhat has just happened? In principle, exactly the same as before but instead of computing the Lasso coefficients for one industry, we did it for ten sequentially. Now, we just have to do some housekeeping and keep only variables that Lasso does *not* set to zero. We illustrate the results in a heat map in @fig-1405.\\index{Graph!Heat map}\n\n:::\n\n::: {.panel-tabset group=\"language\"}\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_factors |>\n  unnest(selected_variables) |>\n  filter(\n    term != \"(Intercept)\",\n    estimate != 0\n  ) |>\n  add_count(term) |>\n  mutate(\n    term = str_remove_all(term, \"NA|ff_|q_\"),\n    term = str_replace_all(term, \"_x_\", \" \"),\n    term = fct_reorder(as_factor(term), n),\n    term = fct_lump_min(term, min = 2),\n    selected = 1\n  ) |>\n  filter(term != \"Other\") |>\n  mutate(term = fct_drop(term)) |>\n  complete(industry, term, fill = list(selected = 0)) |>\n  ggplot(aes(industry,\n    term,\n    fill = as_factor(selected)\n  )) +\n  geom_tile() +\n  scale_x_discrete(guide = guide_axis(angle = 70)) +\n  scale_fill_manual(values = c(\"white\", \"grey30\")) +\n  theme(legend.position = \"None\") +\n  labs(\n    x = NULL, y = NULL,\n    title = \"Selected variables for different industries\"\n  )\n```\n\n::: {.cell-output-display}\n![The figure shows selected variables for different industries. Dark areas indicate that the estimated Lasso regression coefficient is not set to zero. White fields show which variables get assigned a value of exactly zero.](factor-selection-via-machine-learning_files/figure-html/fig-1405-1.png){#fig-1405 fig-alt='Title: Selected variables for different industries. The figure shows which factors and macroeconomic predictors the Lasso model selected for the different industries. In general, there are not many selected variables. The market excess return is selected across all industries except for utilities.' width=2100}\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nselected_factors_figure = (\n  ggplot(\n    selected_factors,\n    aes(x=\"variable\", y=\"industry\")\n  )\n  + geom_tile()\n  + labs(x=\"\", y=\"\", title=\"Selected variables for different industries\")\n  + coord_flip()\n  + scale_x_discrete(limits=reversed)\n  + theme(axis_text_x=element_text(rotation=70, hjust=1), figure_size=(6.4, 6.4))\n)\nselected_factors_figure.show()\n```\n\n::: {.cell-output-display}\n![The figure shows selected variables for different industries. Dark areas indicate that the estimated Lasso regression coefficient is not set to zero. White fields show which variables get assigned a value of exactly zero.](factor-selection-via-machine-learning_files/figure-html/factor-selection-via-machine-learning-fig-1405-py-1.png){fig-pos='htb' fig-alt='Title: Selected variables for different industries. The figure shows which factors and macroeconomic predictors the Lasso model selected for the different industries. In general, there are not many selected variables. The market excess return is selected across all industries except for utilities.'}\n:::\n:::\n\n\n:::\n\nThe heat map in @fig-1405 conveys two main insights.\nFirst, we see a lot of white, which means that many factors, macroeconomic variables, and interaction terms are not relevant for explaining the cross-section of returns across the industry portfolios. In fact, only a couple of factors play a role for several industries. Second, there seems to be quite some heterogeneity across different industries. While barely any variable is selected by Lasso for Utilities, many factors are selected for, e.g., High-Tech and Durable, but they do not coincide at all.\nIn other words, there seems to be a clear picture that we do not need many factors, but Lasso does not provide a factor that consistently provides pricing abilities across industries.\n\n## Key Takeaways\n\n- The `tidymodels` framework in R and the `scikit-learn` framework in Python enable a clean, modular workflow for pre-processing financial data, fitting models, and tuning hyperparameters through cross-validation.\n- Lasso regression is especially useful in high-dimensional settings, as it performs automatic variable selection by setting irrelevant coefficients to zero, offering insights into which factors truly matter.\n- Applying these methods to real-world data shows that only a few factors consistently explain industry portfolio returns, and the relevant predictors vary across industries.\n- The analysis demonstrates practical tools to handle overfitting, model complexity, and interpretability in empirical asset pricing.\n\n## Exercises\n\n1. Write a function that requires three inputs, namely, `y` (a $T$ vector), `X` (a $(T \\times K)$ matrix), and `lambda` and then returns the Ridge estimator (a $K$ vector) for a given penalization parameter $\\lambda$. Recall that the intercept should not be penalized. Therefore, your function should indicate whether $X$ contains a vector of ones as the first column, which should be exempt from the $L_2$ penalty.\n1. Compute the $L_2$ norm ($\\beta'\\beta$) for the regression coefficients based on the predictive regression from the previous exercise for a range of $\\lambda$'s and illustrate the effect of penalization in a suitable figure.\n1. Now, write a function that requires three inputs, namely, `y` (a $T$ vector), `X` (a $(T \\times K)$ matrix), and `lambda` and then returns the Lasso estimator (a $K$ vector) for a given penalization parameter $\\lambda$. Recall that the intercept should not be penalized. Therefore, your function should indicate whether $X$ contains a vector of ones as the first column, which should be exempt from the $L_1$ penalty.\n1. After you understand what Ridge and Lasso regressions are doing, familiarize yourself with the `glmnet` package's documentation. It is a thoroughly tested and well-established package that provides efficient code to compute the penalized regression coefficients for Ridge and Lasso and for combinations, commonly called *Elastic Nets*.\n",
    "supporting": [
      "factor-selection-via-machine-learning_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}