---
title: Changelog
aliases:
  - ../changelog.html
metadata:
  pagetitle: Changelog of Tidy Finance with R
  description-meta: Review all major changes of Tidy Finance with R since the book publication in 2022. 
---

You can find every single change in our [commit history](https://github.com/tidy-finance/website/commits/main). We collect the most important changes for [Tidy Finance with R](index.qmd) in the list below. 

- [June 3, 2024, Commit 23d379f:](https://github.com/tidy-finance/website/commit/23d379faa13a05dc9d2bd0a34df583adf408c477) We fixed a bug in [Univaritate Portfolio Sorts](univariate-portfolio-sorts.qmd), which led to wrong annual returns in Figure 3. 
- [May 15, 2024, Commit 2bb2e07:](https://github.com/tidy-finance/website/commit/2bb2e07db91d4c1886d40616fc7cade0df80b67f) We added a new subsection about creating environment variables to [Setting Up Your Environment](setting-up-your-environment.qmd).
- [May 15, 2024, Commit adccfc9:](https://github.com/tidy-finance/website/commit/adccfc93511cfa16f254e13d86a7649b72b996c9) We updated the filters in CRSP download, so that correct historical information is used and daily and monthly data are aligned.
- [April 19, 2024, Commit d8c4de3:](https://github.com/tidy-finance/website/commit/d8c4de3350da8028eb83aab2cfecb1fe13a34f5b) We updated to `dbplyr` version 2.5.0 and switched to the new `I()` instead of `in_schema()` syntax.
- [March 4, 2024, Commit 6acb50b:](https://github.com/tidy-finance/website/commit/6acb50b4d7ee8415be41731bdd65fc88b1bff76b) We updated the download of monthly and daily CRSP data to the new official file format as distributed by WRDS, see additional information on the [WRDS website](https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/crsp/stocks-and-indices/crsp-stock-and-indexes-version-2/crsp-ciz-faq/). 
- [Feb 13, 2024, Commit 7871900:](https://github.com/tidy-finance/website/commit/78719005211954666662ae2736ee9ecbc9cac02f) We updated the function for cleaning enhanced TRACE used in [TRACE and FISD](trace-and-fisd.qmd) and shown in Appendix [Clean Enhanced TRACE with R](clean-enhanced-trace-with-r.qmd) to reflect the correct time zone (i.e., New York, ET) and require less dependencies. We also updated the respective [gist](https://gist.github.com/patrick-weiss/3a05b3ab281563b2e94858451c2eb3a4).
- [Feb 13, 2024, Commit 5fce497:](https://github.com/tidy-finance/website/commit/5fce497972dfb8498228032f1f2d1ca25b20e93f) We removed the depedency on `googledrive` in [Accessing and Managing Financial Data](accessing-and-managing-financial-data.qmd) because frequently encountered failed downloads due to quota limits on the Google API. 
- [Jan 4, 2024, Commit e9ab1a3:](https://github.com/tidy-finance/website/commit/e9ab1a3f94afae26540d78ecfbc74d49e62f065b) We updated the syntax of `*_join()` functions to use `join_by()` instead of `by`.
- [Dec 10, 2023, Commit 9814a2f:](https://github.com/tidy-finance/website/commit/9814a2f9be1984090c247a88006828a6fc9b606f) We added handling of delisting returns to daily CRSP download. 
- [Oct 14, 2023 Commit b5a7495:](https://github.com/tidy-finance/website/commit/b5a7495259adb6cedc47766e3bfd673c54dba293) We changed the download of daily CRSP data from individual stocks to batches in [WRDS, CRSP, and Compustat](wrds-crsp-and-compustat.qmd).
- [Oct 12, 2023, Commit 48b6b29:](https://github.com/tidy-finance/website/commit/48b6b2964af13c8fc3341f22c06b1dcc7c86d966) We migrated from `keras` to `torch` in [Option Pricing via Machine Learning](option-pricing-via-machine-learning.qmd) for improved environment management.
- [Oct 4, 2023, Commit d4e0717:](https://github.com/tidy-finance/website/commit/d4e071717f1d096c2b1fea9d0f196d025714fea6) We added a new chapter [Setting Up Your Environment](setting-up-your-environment.qmd).
- [Sep 28, 2023, Commit 290a612:](https://github.com/tidy-finance/website/commit/290a61e389e4049d79202966e1243481dfe04dfa) We updated all data sources until 2022-12-31.
- [Sep 23, 2023, Commit f88f6c9:](https://github.com/tidy-finance/website/commit/f88f6c953da0b5a447a295f76cf679a2f5dfa3b6) We switched from `alabama` and `quadprog` to `nloptr` in [Constrained Optimization and Backtesting](constrained-optimization-and-backtesting.qmd) to be more consistent with the optimization in Python and to provide more flexibility with respect to constraints. 
- [June 15, 2023, Commit 47dbb30:](https://github.com/tidy-finance/website/commit/47dbb30efa9615c1d5f7325d75786e584b581cdb) We moved the first usage of `broom:tidy()` from [Fama-Macbeth Regressions](fama-macbeth-regressions.qmd) to [Univariate Portfolio Sorts](univariate-portfolio-sorts.qmd) to clean up the CAPM estimation. 
- [June 12, 2023, Commit e008622:](https://github.com/tidy-finance/website/pull/50/commits/e0086225a35e780b6cc115b905c75576ee40a961) We fixed some inconsencies in notation of portfolio weights. Now, we refer to portfolio weights with $\omega$ throughout the complete book.
- [June 12, 2023, Commit 186ec7b2:](https://github.com/tidy-finance/website/pull/49/commits/186ec7b2c803bfb475fef5c23f9a711a3fb32d1f) We fixed a typo in the discussion of the elastic net in Chapter [Factor Selection via Machine Learning
](factor-selection-via-machine-learning.qmd).
- [May 23, 2023, Commit d5e355c:](https://github.com/tidy-finance/website/commit/d5e355ca6cf117bcc193376124c46ca1b2e9ed1d) We update the workflow to `collect()` tables from `tidy_finance.sqlite`: To make variable selection more obvious, we now explicitly `select()` columns before collecting. As part of the pull request [Commit 91d3077](https://github.com/tidy-finance/website/pull/42/commits/91d3077ee75a3ab71db684001d0562a53031c73c), we now select excess returns instead of net returns in the Chapter [Fama-MacBeth Regressions](fama-macbeth-regressions.qmd).
- [May 20, 2023, Commit be0f0b4:](https://github.com/tidy-finance/website/commit/be0f0b4b156487299369c682a4d47d1d10ec5485) We include `NA`-observations in the Mergent filters in Chapter [TRACE and FISD](trace-and-fisd.qmd).
- [May 17, 2023, Commit 2209bb1:](https://github.com/tidy-finance/website/commit/2209bb133d2080eae52cbbc5ec14e4550ff186d3) We changed the `assign_portfolio()`-functions in Chapters [Univariate Portfolio Sorts](univariate-portfolio-sorts.qmd), [Size Sorts and p-Hacking](size-sorts-and-p-hacking.qmd), [Value and Bivariate Sorts](value-and-bivariate-sorts.qmd), and [Replicating Fama and French Factors](replicating-fama-and-french-factors.qmd). Additionally, we added a small explanation to potential issues with the function for clustered sorting variables in Chapter [Univariate Portfolio Sorts](univariate-portfolio-sorts.qmd).
- [May 12, 2023, Commit 54b76d7:](54b76d7c1977c3759ed8bd641940d17add1a755b) We removed magic numbers in Chapter [Introduction to Tidy Finance](introduction-to-tidy-finance.qmd#the-efficient-frontier) and introduced the `scales` packages already in the introduction chapter to reduce scaling issues in figures. 
- [Mar. 30, 2023, Issue 29:](https://github.com/tidy-finance/website/issues/29) We upgraded to `tidyverse` 2.0.0 and R 4.2.3 and removed all explicit loads of `lubridate`.
- [Feb. 15, 2023, Commit bfda6af: ](https://github.com/tidy-finance/website/commit/bfda6af6169a42f433568e32b7a9cce06cb948ac) We corrected an error in the calculation of the annualized average return volatility in the Chapter [Introduction to Tidy Finance](introduction-to-tidy-finance.qmd#the-efficient-frontier).
- [Mar. 06, 2023, Commit 857f0f5: ](https://github.com/tidy-finance/website/commit/857f0f5893a8e7e4c2b4475e1461ebf3d0abe2d6) We corrected an error in the label of [Figure 6](introduction-to-tidy-finance.qmd#fig-106), which wrongly claimed to show the efficient tangency portfolio.
- [Mar. 09, 2023, Commit fae4ac3: ](https://github.com/tidy-finance/website/commit/fae4ac3fd12797d66a48f43af3d8e84ded694f13) We corrected a typo in the definition of the power utility function in Chapter [Portfolio Performance](parametric-portfolio-policies.qmd#portfolio-performance). The utility function implemented in the code is now consistent with the text. 
